// Auto-generated by scripts/compute-sidebar-width.mjs — do not edit.
// Recalculate: pnpm compute:sidebar-width
// Heuristic: Inter 14px medium, ~7.3 px/char ±5 px (spec §15.12).
export const SIDEBAR_DEFAULT_WIDTH = 180;
