/* eslint-disable */
/**
 * AUTO-GENERATED — do not edit by hand.
 * Regenerate via: pnpm gen:models
 * Source: sidecar_kuro.models (PYTHONPATH=python-core)
 */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SidecarKuroModels {
  AlternativesResultModel?: AlternativesResultModel;
  BenchmarkResultDict?: BenchmarkResultDict;
  BenchmarkResultModel?: BenchmarkResultModel;
  CheckStructuresParams?: CheckStructuresParams;
  CommitDesignResultParams?: CommitDesignResultParams;
  DesignResultResponseModel?: DesignResultResponseModel;
  DesignSdmPrimersParams?: DesignSdmPrimersParams;
  DomainEntry?: DomainEntry;
  DomainInfoModel?: DomainInfoModel;
  EvaluatePrimerParams?: EvaluatePrimerParams;
  EvolveproStepStatsModel?: EvolveproStepStatsModel;
  ExcludedRange?: ExcludedRange;
  ExportAllParams?: ExportAllParams;
  ExportBenchmarkCsvParams?: ExportBenchmarkCsvParams;
  ExportExcelParams?: ExportExcelParams;
  ExportMacrogenParams?: ExportMacrogenParams;
  ExportMappingParams?: ExportMappingParams;
  ExportMappingResultModel?: ExportMappingResultModel;
  ExportOrderItem?: ExportOrderItem;
  ExportOrderParams?: ExportOrderParams;
  ExportOrderResultModel?: ExportOrderResultModel;
  FailedMutationModel?: FailedMutationModel;
  FetchDomainsParams?: FetchDomainsParams;
  FetchStructureParams?: FetchStructureParams;
  FileExportResultModel?: FileExportResultModel;
  GetAlternativesParams?: GetAlternativesParams;
  LandscapeEntry?: LandscapeEntry;
  LoadEvolveproParams?: LoadEvolveproParams;
  LoadFastaParams?: LoadFastaParams;
  LoadWorkspaceParams?: LoadWorkspaceParams;
  OffTargetHitModel?: OffTargetHitModel;
  ParseMutationsTextParams?: ParseMutationsTextParams;
  PlateMappingItem?: PlateMappingItem;
  PolymeraseProfileModel?: PolymeraseProfileModel;
  RescueStatsModel?: RescueStatsModel;
  RescuedMutationModel?: RescuedMutationModel;
  RetryFailedParams?: RetryFailedParams;
  RunBenchmarkParams?: RunBenchmarkParams;
  SaveCustomPolymeraseResultModel?: SaveCustomPolymeraseResultModel;
  SaveJsonParams?: SaveJsonParams;
  SaveWorkspaceParams?: SaveWorkspaceParams;
  SdmPrimerResultModel?: SdmPrimerResultModel;
  SearchUniprotParams?: SearchUniprotParams;
  SettingsBundle?: SettingsBundle;
  SettingsLoadRequest?: SettingsLoadRequest;
  SettingsLoadResponse?: SettingsLoadResponse;
  SettingsNetwork?: SettingsNetwork;
  SettingsSaveRequest?: SettingsSaveRequest;
  SettingsSaveResponse?: SettingsSaveResponse;
  SettingsSidecar?: SettingsSidecar;
  SettingsTelemetry?: SettingsTelemetry;
  SortingEntry?: SortingEntry;
  SwapPrimerParams?: SwapPrimerParams;
  WorkspaceCacheModel?: WorkspaceCacheModel;
  WorkspaceInputsModel?: WorkspaceInputsModel;
  WorkspaceModel?: WorkspaceModel;
  WorkspaceResultsModel?: WorkspaceResultsModel;
  WorkspaceSettingsModel?: WorkspaceSettingsModel;
  WorkspaceUiModel?: WorkspaceUiModel;
  WorkspaceV1Data?: WorkspaceV1Data;
  WorkspaceV2Data?: WorkspaceV2Data;
  WorkspaceV3Data?: WorkspaceV3Data;
}
export interface AlternativesResultModel {
  candidates?: SdmPrimerResultModel[];
  count?: number | null;
  mutation?: string | null;
  [k: string]: unknown;
}
export interface SdmPrimerResultModel {
  aa_position: number;
  candidate_count?: number | null;
  candidate_fwd_count?: number | null;
  candidate_rev_count?: number | null;
  codon_pos: number;
  forward_seq: string;
  fwd_len: number;
  gc_fwd: number;
  gc_rev: number;
  hairpin_dg_fwd?: number | null;
  hairpin_dg_rev?: number | null;
  hairpin_tm_fwd?: number | null;
  hairpin_tm_rev?: number | null;
  has_offtarget: boolean;
  homodimer_dg_fwd?: number | null;
  homodimer_dg_rev?: number | null;
  homodimer_tm_fwd?: number | null;
  homodimer_tm_rev?: number | null;
  mt_codon: string;
  mutation: string;
  offtarget_fwd?: OffTargetHitModel[] | null;
  offtarget_rev?: OffTargetHitModel[] | null;
  overlap_len: number;
  overlap_mode?: ("partial" | "full") | null;
  overlap_seq: string;
  penalty: number;
  rev_len: number;
  reverse_seq: string;
  synthesis_score_fwd?: number | null;
  synthesis_score_rev?: number | null;
  tm_condition_met: boolean;
  tm_no_fwd: number;
  tm_no_rev: number;
  tm_overlap: number;
  tolerance_fwd?: number | null;
  tolerance_rev?: number | null;
  tolerance_used: number;
  warnings?: string[];
  wt_codon: string;
  [k: string]: unknown;
}
export interface OffTargetHitModel {
  match_length: number;
  match_seq: string;
  position: number;
  strand: "sense" | "antisense";
  tm: number;
  [k: string]: unknown;
}
/**
 * Metrics returned by evaluate_selection() for a single strategy.
 */
export interface BenchmarkResultDict {
  domain_coverage?: number;
  hit_rate?: number;
  hits?: number;
  mean_fitness?: number;
  n_selected?: number;
  n_trials?: number;
  position_coverage?: number;
  structural_spread?: number;
  threshold?: number;
  unique_positions?: number;
  [k: string]: unknown;
}
export interface BenchmarkResultModel {
  domain_coverage: number;
  hit_rate: number;
  hits: number;
  mean_fitness: number;
  n_selected: number;
  n_trials?: number | null;
  position_coverage: number;
  structural_spread: number;
  threshold: number;
  unique_positions: number;
  [k: string]: unknown;
}
export interface CheckStructuresParams {
  /**
   * @maxItems 20
   */
  accessions?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ];
  [k: string]: unknown;
}
export interface CommitDesignResultParams {
  candidate_idx?: number;
  mutation?: string;
  [k: string]: unknown;
}
export interface DesignResultResponseModel {
  cancelled?: boolean | null;
  failed_mutations?: FailedMutationModel[];
  rescue_stats?: RescueStatsModel | null;
  rescued_mutations?: RescuedMutationModel[] | null;
  results?: SdmPrimerResultModel[];
  success_count: number;
  total_count: number;
  [k: string]: unknown;
}
export interface FailedMutationModel {
  mutation: string;
  rank: number;
  reason: string;
  [k: string]: unknown;
}
export interface RescueStatsModel {
  auto_relax: number;
  pool_cascade: number;
  pool_variants_tried: number;
  positions_attempted: number;
  [k: string]: unknown;
}
export interface RescuedMutationModel {
  original: string;
  penalty?: number | null;
  rescued_by: string;
  stage?: number | null;
  substitute?: string | null;
  tolerance_used?: number | null;
  type:
    | "pool_cascade"
    | "auto_relax"
    | "auto_suggestion"
    | "same_position"
    | "diff_position"
    | "auto_suggestion_l1"
    | "auto_suggestion_l2"
    | "auto_suggestion_l3"
    | "auto_suggestion_l4";
  [k: string]: unknown;
}
export interface DesignSdmPrimersParams {
  auto_relax?: boolean;
  codon_strategy?: string;
  fasta_path: string;
  fwd_len_max?: number | null;
  fwd_len_min?: number | null;
  gc_max?: number;
  gc_min?: number;
  mutations_csv_or_text?: string;
  organism?: string;
  overlap_len?: number | null;
  overlap_mode?: "partial" | "full";
  polymerase?: string;
  rescue_pool?: string[];
  rev_len_max?: number | null;
  rev_len_min?: number | null;
  seed?: number | null;
  target_start?: number;
  tm_fwd_target?: number | null;
  tm_overlap_target?: number | null;
  tm_rev_target?: number | null;
  [k: string]: unknown;
}
/**
 * A single protein domain passed from the frontend to selection/benchmark handlers.
 */
export interface DomainEntry {
  end: number;
  name: string;
  start: number;
  [k: string]: unknown;
}
export interface DomainInfoModel {
  db: string;
  end: number;
  id: string;
  name: string;
  start: number;
  [k: string]: unknown;
}
export interface EvaluatePrimerParams {
  fasta_path: string;
  forward_seq?: string;
  mutation?: string;
  overlap_len?: number;
  reverse_seq?: string;
  [k: string]: unknown;
}
export interface EvolveproStepStatsModel {
  domain_selected?: number | null;
  pareto_exchanges?: number | null;
  position_filter_removed?: number | null;
  [k: string]: unknown;
}
export interface ExcludedRange {
  end: number;
  start: number;
  [k: string]: unknown;
}
/**
 * Params for `export_all` RPC method (6-file batch export).
 */
export interface ExportAllParams {
  amount?: "0.05" | "0.2";
  bom?: boolean;
  echo_transfer_vol?: number;
  fwd_plate_name?: string;
  janus_transfer_vol?: number;
  output_dir: string;
  project_id?: string | null;
  purification?: "MOPC";
  rev_plate_name?: string;
  [k: string]: unknown;
}
export interface ExportBenchmarkCsvParams {
  bom?: boolean;
  filepath: string;
  results?: {
    [k: string]: BenchmarkResultDict;
  };
  [k: string]: unknown;
}
export interface ExportExcelParams {
  benchmark_raw?: unknown;
  dedup_info?: {
    [k: string]: string[];
  } | null;
  filepath: string;
  kuma_version?: string | null;
  mappings?: PlateMappingItem[] | null;
  project_id?: string | null;
  report_data?: unknown;
  rescued_info?: RescuedMutationModel[] | null;
  [k: string]: unknown;
}
export interface PlateMappingItem {
  mt_codon?: string | null;
  mutation: string;
  primer_name: string;
  primer_type: string;
  sequence: string;
  tm?: number | null;
  tm_overlap?: number | null;
  well: string;
  wt_codon?: string | null;
  [k: string]: unknown;
}
/**
 * Params for `export_macrogen` RPC method (Macrogen Plate Oligo .xls).
 */
export interface ExportMacrogenParams {
  amount?: "0.05" | "0.2";
  fwd_plate_name?: string;
  output_path: string;
  project_id?: string | null;
  purification?: "MOPC";
  rev_plate_name?: string;
  [k: string]: unknown;
}
export interface ExportMappingParams {
  bom?: boolean;
  dedup_info?: {
    [k: string]: string[];
  } | null;
  filepath: string;
  format?: "echo" | "janus";
  mappings?: PlateMappingItem[] | null;
  transfer_vol?: number | null;
  [k: string]: unknown;
}
export interface ExportMappingResultModel {
  checksum_path?: string | null;
  filepath: string;
  format: "echo" | "janus";
  manifest_path?: string | null;
  primer_count: number;
  success?: true;
  [k: string]: unknown;
}
export interface ExportOrderItem {
  forward_seq: string;
  mutation: string;
  reverse_seq: string;
  [k: string]: unknown;
}
export interface ExportOrderParams {
  bom?: boolean;
  filepath: string;
  format?: "idt" | "twist";
  results?: ExportOrderItem[] | null;
  [k: string]: unknown;
}
export interface ExportOrderResultModel {
  checksum_path?: string | null;
  filepath: string;
  format: "idt" | "twist";
  manifest_path?: string | null;
  primer_count: number;
  success?: true;
  [k: string]: unknown;
}
export interface FetchDomainsParams {
  accession?: string;
  [k: string]: unknown;
}
export interface FetchStructureParams {
  accession?: string;
  [k: string]: unknown;
}
export interface FileExportResultModel {
  checksum_path?: string | null;
  filepath: string;
  manifest_path?: string | null;
  success?: true;
  [k: string]: unknown;
}
export interface GetAlternativesParams {
  mutation?: string;
  [k: string]: unknown;
}
export interface LandscapeEntry {
  fitness: number;
  variant: string;
  [k: string]: unknown;
}
export interface LoadEvolveproParams {
  distance_mode?: "auto" | "1d" | "3d";
  domain_diversity?: boolean;
  domain_overlap_policy?: "first" | "largest";
  domain_quota_min?: number;
  domain_strategy?: string;
  domains?: DomainEntry[];
  entropy_weight?: number;
  evolvepro_round?: number;
  excluded_ranges?: ExcludedRange[];
  filepath?: string;
  linker_handling?: "include" | "exclude" | "separate-bin";
  max_per_position?: number;
  pareto_diversity?: boolean;
  pool_multiplier?: number;
  ref_seq?: string;
  round_size?: number;
  structure_accession?: string | null;
  top_n?: number;
  [k: string]: unknown;
}
export interface LoadFastaParams {
  filepath: string;
  [k: string]: unknown;
}
export interface LoadWorkspaceParams {
  filepath: string;
  [k: string]: unknown;
}
export interface ParseMutationsTextParams {
  text?: string;
  [k: string]: unknown;
}
export interface PolymeraseProfileModel {
  default_overlap_mode?: ("partial" | "full") | null;
  dna_conc: number;
  dntp_conc: number;
  fwd_len_max?: number | null;
  fwd_len_min?: number | null;
  max_gc: number;
  max_size: number;
  max_tm: number;
  max_tm_diff: number;
  min_3prime_dist?: number | null;
  min_gc: number;
  min_size: number;
  min_tm: number;
  name: string;
  opt_size: number;
  opt_tm: number;
  opt_tm_fwd?: number | null;
  opt_tm_overlap?: number | null;
  opt_tm_rev?: number | null;
  overlap_len?: number | null;
  rev_len_max?: number | null;
  rev_len_min?: number | null;
  salt_correction: string;
  salt_divalent: number;
  salt_monovalent: number;
  tm_method: string;
  [k: string]: unknown;
}
export interface RetryFailedParams {
  codon_strategy?: string;
  fasta_path: string;
  fwd_len_max?: number | null;
  fwd_len_min?: number | null;
  gc_max?: number;
  gc_min?: number;
  mutation?: string;
  num_return?: number;
  organism?: string;
  overlap_len?: number | null;
  overlap_mode?: "partial" | "full";
  polymerase?: string;
  rev_len_max?: number | null;
  rev_len_min?: number | null;
  target_start?: number;
  tm_fwd_target?: number;
  tm_overlap_target?: number;
  tm_rev_target?: number;
  tol_max?: number;
  [k: string]: unknown;
}
export interface RunBenchmarkParams {
  distance_mode?: "auto" | "1d" | "3d";
  domain_strategy?: string;
  domains?: DomainEntry[];
  entropy_weight?: number;
  ground_truth?: {
    [k: string]: number;
  };
  landscape?: LandscapeEntry[];
  max_per_position?: number;
  n_random_trials?: number;
  n_select?: number;
  pool_multiplier?: number;
  random_seed?: number | null;
  strategies?: string[];
  structure_accession?: string | null;
  top_percentile?: number;
  [k: string]: unknown;
}
export interface SaveCustomPolymeraseResultModel {
  name: string;
  success?: true;
  [k: string]: unknown;
}
export interface SaveJsonParams {
  data: unknown;
  filepath: string;
  [k: string]: unknown;
}
export interface SaveWorkspaceParams {
  data: unknown;
  filepath: string;
  [k: string]: unknown;
}
export interface SearchUniprotParams {
  gene_name?: string;
  known_accession?: string;
  organism?: string;
  translation?: string;
  [k: string]: unknown;
}
/**
 * Complete application preferences bundle persisted to ~/.kuma/preferences.json.
 */
export interface SettingsBundle {
  default_workspace_folder?: string | null;
  language?: string;
  network?: SettingsNetwork;
  sidecar?: SettingsSidecar;
  telemetry?: SettingsTelemetry;
  theme?: "light" | "dark" | "auto";
  [k: string]: unknown;
}
/**
 * Network consent flags and offline mode for Settings.
 */
export interface SettingsNetwork {
  consent_alphafold?: boolean;
  consent_blast?: boolean;
  consent_interpro?: boolean;
  consent_uniprot?: boolean;
  offline_mode?: boolean;
  [k: string]: unknown;
}
/**
 * Sidecar runtime tuning parameters for Settings.
 */
export interface SettingsSidecar {
  cancel_timeout_secs?: number;
  concurrency_default?: number;
  persist_on_cancel?: "partial" | "discard";
  [k: string]: unknown;
}
/**
 * Telemetry opt-in flags for Settings.
 */
export interface SettingsTelemetry {
  anonymous_stats?: boolean;
  crash_log_auto_send?: boolean;
  [k: string]: unknown;
}
/**
 * Empty request body for settings_load RPC.
 */
export interface SettingsLoadRequest {
  [k: string]: unknown;
}
/**
 * Response body for settings_load RPC.
 */
export interface SettingsLoadResponse {
  settings: SettingsBundle;
  [k: string]: unknown;
}
/**
 * Request body for settings_save RPC -- full SettingsBundle payload.
 */
export interface SettingsSaveRequest {
  settings: SettingsBundle;
  [k: string]: unknown;
}
/**
 * Response body for settings_save RPC.
 */
export interface SettingsSaveResponse {
  ok: boolean;
  path: string;
  [k: string]: unknown;
}
export interface SortingEntry {
  desc: boolean;
  id: string;
  [k: string]: unknown;
}
export interface SwapPrimerParams {
  candidate_idx?: number;
  mutation?: string;
  swap_type?: "both" | "fwd" | "rev";
  [k: string]: unknown;
}
export interface WorkspaceCacheModel {
  benchmarkResults?: {
    [k: string]: BenchmarkResultModel;
  } | null;
  evolveproFilteredCount?: number | null;
  evolveproParetoExchanges?: number | null;
  evolveproStepStats?: EvolveproStepStatsModel | null;
  evolveproTotalCount?: number | null;
  [k: string]: unknown;
}
export interface WorkspaceInputsModel {
  evolveproCsvPath: string;
  fastaPath: string;
  mutationInputMode: "text" | "evolvepro" | "multi-evolve";
  mutationText: string;
  selectedGene: string;
  [k: string]: unknown;
}
export interface WorkspaceModel {
  [k: string]: unknown;
}
export interface WorkspaceResultsModel {
  customCandidates: {
    [k: string]: SdmPrimerResultModel[];
  };
  dedupInfo: {
    [k: string]: string[];
  };
  designResults: SdmPrimerResultModel[];
  failedMutations: FailedMutationModel[];
  manuallySwapped: {
    [k: string]: "fwd" | "rev" | "both";
  };
  plateMappings: PlateMappingItem[];
  rescuedMutationDetails?: RescuedMutationModel[] | null;
  successCount: number;
  totalCount: number;
  [k: string]: unknown;
}
export interface WorkspaceSettingsModel {
  autoRedesignOnLoad?: boolean | null;
  benchmarkRandomSeed?: number | null;
  benchmarkRandomTrials?: number | null;
  benchmarkTopPercentile?: number | null;
  codonStrategy: "closest" | "optimal";
  disabledDomains?: string[] | null;
  distanceMode?: ("auto" | "1d" | "3d") | null;
  domainDiversityEnabled?: boolean | null;
  domainOverlapPolicy?: ("first" | "largest") | null;
  domainQuotaMin?: number | null;
  domainStrategy?: ("proportional" | "equal") | null;
  domains?: DomainInfoModel[] | null;
  entropyWeight?: number | null;
  entropyWeightEnabled?: boolean | null;
  evolveproRound?: number | null;
  fillOnFailure?: boolean | null;
  fwdLenMax?: number | null;
  fwdLenMin?: number | null;
  gcMax: number;
  gcMin: number;
  linkerHandling?: ("include" | "exclude" | "separate-bin") | null;
  maxPerPosition?: number | null;
  maxPrimers: number;
  organism?: string | null;
  overlapMode?: ("partial" | "full") | null;
  paretoDiversityEnabled?: boolean | null;
  paretoPoolMultiplier?: number | null;
  pipelineMode?: boolean | null;
  positionDiversityEnabled?: boolean | null;
  primerLenEnabled?: boolean | null;
  rescuedMutations?: string[] | null;
  revLenMax?: number | null;
  revLenMin?: number | null;
  roundSize?: number | null;
  saveCache?: boolean | null;
  selectedPolymerase?: string | null;
  tmFwdTarget: number;
  tmOverlapTarget: number;
  tmRevTarget: number;
  uniprotAccession?: string | null;
  [k: string]: unknown;
}
export interface WorkspaceUiModel {
  tableSorting: SortingEntry[];
  [k: string]: unknown;
}
export interface WorkspaceV1Data {
  codonStrategy: "closest" | "optimal";
  customCandidates: {
    [k: string]: SdmPrimerResultModel[];
  };
  dedupInfo: {
    [k: string]: string[];
  };
  designResults: SdmPrimerResultModel[];
  disabledDomains?: string[] | null;
  domainDiversityEnabled?: boolean | null;
  domainStrategy?: ("proportional" | "equal") | null;
  domains?: DomainInfoModel[] | null;
  entropyWeight?: number | null;
  entropyWeightEnabled?: boolean | null;
  evolveproCsvPath: string;
  evolveproFilteredCount?: number | null;
  evolveproParetoExchanges?: number | null;
  evolveproRound?: number | null;
  evolveproStepStats?: EvolveproStepStatsModel | null;
  evolveproTotalCount?: number | null;
  failedMutations: FailedMutationModel[];
  fastaPath: string;
  fillOnFailure?: boolean | null;
  fwdLenMax?: number | null;
  fwdLenMin?: number | null;
  gcMax: number;
  gcMin: number;
  manuallySwapped: {
    [k: string]: "fwd" | "rev" | "both";
  };
  maxPerPosition?: number | null;
  maxPrimers: number;
  mutationInputMode: "text" | "evolvepro" | "multi-evolve";
  mutationText: string;
  organism?: string | null;
  overlapMode?: ("partial" | "full") | null;
  paretoDiversityEnabled?: boolean | null;
  pipelineMode?: boolean | null;
  plateMappings: PlateMappingItem[];
  positionDiversityEnabled?: boolean | null;
  primerLenEnabled?: boolean | null;
  rescuedMutations?: string[] | null;
  revLenMax?: number | null;
  revLenMin?: number | null;
  roundSize?: number | null;
  selectedGene: string;
  successCount: number;
  tableSorting: SortingEntry[];
  tmFwdTarget: number;
  tmOverlapTarget: number;
  tmRevTarget: number;
  totalCount: number;
  uniprotAccession?: string | null;
  version: 1;
  [k: string]: unknown;
}
export interface WorkspaceV2Data {
  cache?: WorkspaceCacheModel | null;
  inputs: WorkspaceInputsModel;
  results: WorkspaceResultsModel;
  settings: WorkspaceSettingsModel;
  ui: WorkspaceUiModel;
  version: 2;
  [k: string]: unknown;
}
export interface WorkspaceV3Data {
  active_round_id?: string | null;
  cache?: WorkspaceCacheModel | null;
  inputs: WorkspaceInputsModel;
  results: WorkspaceResultsModel;
  rounds?: unknown[];
  schema_version: "0.3";
  settings: WorkspaceSettingsModel;
  ui: WorkspaceUiModel;
  [k: string]: unknown;
}
