/* eslint-disable */
/**
 * AUTO-GENERATED — do not edit by hand.
 * Regenerate via: pnpm gen:models
 * Source: sidecar_evolvepro.models (PYTHONPATH=python-core)
 */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SidecarEvolveproModels {
  CondaCreateEnvResponse?: CondaCreateEnvResponse;
  CondaStatusResponse?: CondaStatusResponse;
  CondaVerifyResponse?: CondaVerifyResponse;
  EnvStatusResponse?: EnvStatusResponse;
  Esm2ModelRecommendation?: Esm2ModelRecommendation;
  Esm2RecommendationResponse?: Esm2RecommendationResponse;
  EvolveProCancelRequest?: EvolveProCancelRequest;
  EvolveProDetectResponse?: EvolveProDetectResponse;
  EvolveProEmbeddingCacheStatusRequest?: EvolveProEmbeddingCacheStatusRequest;
  EvolveProEmbeddingCacheStatusResponse?: EvolveProEmbeddingCacheStatusResponse;
  EvolveProRunProgress?: EvolveProRunProgress;
  EvolveProRunRequest?: EvolveProRunRequest;
  EvolveProRunResult?: EvolveProRunResult;
  EvolveProRunResultRequest?: EvolveProRunResultRequest;
  EvolveProRunResultResponse?: EvolveProRunResultResponse;
  EvolveProRunStartResponse?: EvolveProRunStartResponse;
}
/**
 * Response body for conda.create_env RPC (returned after streaming completes).
 */
export interface CondaCreateEnvResponse {
  error?: string | null;
  ok: boolean;
  [k: string]: unknown;
}
/**
 * Response body for conda.detect RPC.
 */
export interface CondaStatusResponse {
  conda_exe?: string | null;
  installed: boolean;
  version?: string | null;
  [k: string]: unknown;
}
/**
 * Response body for conda.verify_env RPC.
 */
export interface CondaVerifyResponse {
  error?: string | null;
  ok: boolean;
  [k: string]: unknown;
}
/**
 * Response body for conda.detect_env RPC.
 */
export interface EnvStatusResponse {
  env_path?: string | null;
  exists: boolean;
  packages?: {
    [k: string]: string | null;
  };
  [k: string]: unknown;
}
/**
 * RAM gate for a single ESM2 model.
 */
export interface Esm2ModelRecommendation {
  download_url: string;
  expected_bytes: number;
  label: string;
  min_ram_gb: number;
  model_id: string;
  reason: string;
  recommended_ram_gb: number;
  size_label: string;
  status: "safe" | "caution" | "blocked" | "unknown";
  [k: string]: unknown;
}
/**
 * Cross-platform ESM2 model recommendation response.
 */
export interface Esm2RecommendationResponse {
  arch: string;
  cpu_cores?: number | null;
  disk_free_gb?: number | null;
  gpu_available?: boolean;
  gpu_kind?: string | null;
  models?: Esm2ModelRecommendation[];
  os: string;
  ram_gb?: number | null;
  recommended_label?: string | null;
  recommended_model_id?: string | null;
  warnings?: string[];
  [k: string]: unknown;
}
/**
 * Request body for evolvepro_cancel RPC.
 */
export interface EvolveProCancelRequest {
  run_id: string;
  [k: string]: unknown;
}
/**
 * Response body for evolvepro_detect RPC.
 */
export interface EvolveProDetectResponse {
  cached_models?: {
    [k: string]: string;
  };
  env_found: boolean;
  env_path?: string | null;
  evolvepro_version?: string | null;
  weights_cached?: boolean;
  weights_path?: string | null;
  [k: string]: unknown;
}
/**
 * Request body for evolvepro.embedding_cache_status RPC.
 */
export interface EvolveProEmbeddingCacheStatusRequest {
  esm2_model_id:
    | "esm2_t6_8M_UR50D"
    | "esm2_t12_35M_UR50D"
    | "esm2_t30_150M_UR50D"
    | "esm2_t33_650M_UR50D"
    | "esm2_t36_3B_UR50D"
    | "esm2_t48_15B_UR50D";
  wt_sequence: string;
  [k: string]: unknown;
}
/**
 * Response body for evolvepro.embedding_cache_status RPC.
 */
export interface EvolveProEmbeddingCacheStatusResponse {
  cache_dir: string;
  cached: boolean;
  estimate_basis?: string | null;
  estimate_seconds?: number | null;
  n_variants: number;
  [k: string]: unknown;
}
/**
 * Progress notification payload streamed during evolvepro_run.
 */
export interface EvolveProRunProgress {
  current: number;
  message?: string;
  result?: EvolveProRunResult | null;
  run_id: string;
  stage: "detect" | "loading" | "embedding" | "scoring" | "selecting" | "done" | "error";
  total: number;
  [k: string]: unknown;
}
/**
 * Terminal result payload for an EVOLVEpro run.
 */
export interface EvolveProRunResult {
  elapsed_sec: number;
  output_csv: string;
  run_id: string;
  top_variants?: string[];
  [k: string]: unknown;
}
/**
 * Request body for evolvepro_run RPC.
 */
export interface EvolveProRunRequest {
  env_name?: string;
  esm2_model_id:
    | "esm2_t6_8M_UR50D"
    | "esm2_t12_35M_UR50D"
    | "esm2_t30_150M_UR50D"
    | "esm2_t33_650M_UR50D"
    | "esm2_t36_3B_UR50D"
    | "esm2_t48_15B_UR50D";
  input_csv: string;
  n_rounds: number;
  output_dir: string;
  round_files?: string[];
  top_n?: number;
  wt_fasta?: string | null;
  wt_sequence?: string;
  [k: string]: unknown;
}
/**
 * Request body for evolvepro.run_result RPC.
 */
export interface EvolveProRunResultRequest {
  output_dir: string;
  [k: string]: unknown;
}
/**
 * Response body for evolvepro.run_result RPC.
 *
 * Note: top_variants is list[dict] (full rows from top_variants.csv), unlike
 * the streaming EvolveProRunResult which carries list[str] variant names only.
 * n_predictions is the row count of df_test.csv. elapsed_sec is optional
 * because this handler reads from disk without a start timestamp.
 */
export interface EvolveProRunResultResponse {
  elapsed_sec?: number | null;
  n_predictions: number;
  output_csv: string;
  top_variants?: {
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * Response body for evolvepro_run RPC (returned immediately on spawn).
 */
export interface EvolveProRunStartResponse {
  run_id: string;
  [k: string]: unknown;
}
