// AUTO-GENERATED by scripts/gen-whatsnew.mjs from CHANGELOG.md. Do not edit by hand.
// Run `pnpm gen:whatsnew` after updating CHANGELOG.md.
export interface WhatsNewItem {
  label: string;
  detail: string;
}

export const WHATS_NEW_VERSION = "0.13.6";

export const WHATS_NEW_ITEMS: WhatsNewItem[] = [
  { label: "Fixed", detail: "outbound HTTPS (Kuro UniProt search, AlphaFold, EBI BLAST, ESM) failed on the packaged macOS app with `CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate`. macOS OpenSSL does not read the Keychain and the frozen app has no b…" },
  { label: "Fixed", detail: "MAME step 1.1 \"Generate Barcode Package\" no longer requires the output directory to live inside the project root (it failed with `output_dir must be inside project_root`). `mame_context.json` stores paths relative when the output is inside…" },
  { label: "Added", detail: "loading sample data populates a precomputed analysis result (`samples/mame/sample_analysis_result.json`, serialized from the real demux/consensus/verdict/health pipeline) so the Per-plate verdict breakdown renders instead of showing \"Setup…" },
  { label: "Added", detail: "loading sample data seeds the Build EVOLVEpro Input form (layout / GC data / Agilent rep-batch / previous EVOLVEpro) from the bundled `06`/`08`/`09`/`10` sample xlsx files; fields already set by the user are preserved." },
];
