// AUTO-GENERATED by scripts/gen-whatsnew.mjs from CHANGELOG.md. Do not edit by hand.
// Run `pnpm gen:whatsnew` after updating CHANGELOG.md.
export interface WhatsNewItem {
  label: string;
  detail: string;
}

export const WHATS_NEW_VERSION = "0.15.15";

export const WHATS_NEW_ITEMS: WhatsNewItem[] = [
  { label: "Added", detail: "MAME compares each well against its own expected variant and against every other one after the run, and says so on the review screen when the second agreement is high and the first is near zero. The message carries the counts it was comput…" },
  { label: "Added", detail: "Every run records how the wells were placed, whether from a layout that was given, a sample map, or the order of the expected sheet, along with the workbook it read. A verdict table that looks ordinary is now traceable to the decision that…" },
  { label: "Changed", detail: "Choosing a different run folder, expected workbook, reference or sample map clears what the previous run produced. The screen used to keep the verdicts, the plate map and the two instrument-file notices next to inputs that no longer made t…" },
  { label: "Changed", detail: "The analyze screens carry no Janus text at all. The instrument controls moved to step 3 in v0.15.12 but the notice about the files a run wrote stayed behind, which is the one thing an operator who stops at a sequencing verdict has no use f…" },
  { label: "Changed", detail: "Step 3 shows the instrument settings on the page instead of behind a button that opened a dialog. The deck preview and the row preview are what the operator checks before an export, and they were being read through a modal on a screen that…" },
  { label: "Changed", detail: "A run no longer writes the instrument mapping file. Analyzing produced the 9-column robot sheet next to the workbook whether or not anyone intended to touch a robot, which made step 3 a formality for an operator who only wanted a sequencin…" },
  { label: "Fixed", detail: "A well layout MAME inferred for one run no longer comes back from a restored project as though the operator had chosen it. It used to be stored with the verdicts, restored into the input state, and sent to the next run as a layout that was…" },
  { label: "Fixed", detail: "An amplicon that cannot be extracted says which of the three reasons applied. It reported every case as primer boundaries that were not unique, including the ordinary one where a bare CDS reference simply does not contain the primer tails,…" },
];
