// AUTO-GENERATED by scripts/gen-whatsnew.mjs from CHANGELOG.md. Do not edit by hand.
// Run `pnpm gen:whatsnew` after updating CHANGELOG.md.
export interface WhatsNewItem {
  label: string;
  detail: string;
}

export const WHATS_NEW_VERSION = "0.13.37";

export const WHATS_NEW_ITEMS: WhatsNewItem[] = [
  { label: "Fixed", detail: "Export All opens on the project design folder and creates it first, so a project that has never been exported to is still a valid destination. Choosing somewhere else still works and behaves as before." },
  { label: "Fixed", detail: "The files Export All writes are recorded in the project manifest, each under a type taken from its filename suffix. Steps that look for an earlier output can now find one. Files with an unrecognised suffix are skipped rather than filed und…" },
];
