# ruff: noqa: S101
"""Unit tests for kuma_core.mame.ingest.combinatorial_demux.

Coverage:
- _extract_barcode_prefix: tail present / tail absent fallback
- _extract_f_prefix / _extract_r_prefix: tail stripping
- load_barcode_prefixes: F/R prefix extraction from xlsx-like data
- load_barcodes: full-sequence loading (legacy backward compat)
- _find_best_barcode: exact match, 1-mismatch fuzzy, ambiguous drop
- _demux_read_anchored: anchor-based fuzzy demux, strand normalisation
- _demux_read: legacy exact-match (backward compat)
- run_combinatorial_demux: end-to-end with synthetic FASTQ + synthetic reference

Synthetic data strategy
-----------------------
Reference: 60 bp DNA (short enough to build synthetic reads quickly).
Reads: generated by embedding known F/R barcode prefixes around an amplicon
       that aligns to the reference at full span.
"""

from __future__ import annotations

import gzip
from pathlib import Path

import pytest

from kuma_core.mame.ingest.combinatorial_demux import (
    _demux_read,
    _demux_read_anchored,
    _extract_barcode_prefix,
    _find_best_barcode,
    _reverse_complement,
    load_barcode_prefixes,
    load_barcodes,
    run_combinatorial_demux,
)

# ---------------------------------------------------------------------------
# Synthetic constants
# ---------------------------------------------------------------------------

# Short synthetic reference (60 bp)
_REF_SEQ = "ATGGCTTGCTCTGTATCCACTGAGAACGTATCTTTCACTGAGACTGAAACTGAGACCCGT"

# Barcode prefix sequences (without annealing tails); matches xlsx structure.
_F_BARCODES = [
    "AATCCCACTAC",  # F1 (11 bp)
    "TGAACTGAGCG",  # F2 (11 bp)
    "TATCTGACCTT",  # F3 (11 bp)
    "ATATGAGACG",   # F4 (10 bp)
    "CGCTCATTAG",   # F5 (10 bp)
    "TAATCTCGTC",   # F6 (10 bp)
    "GCGCGATTTT",   # F7 (10 bp)
    "AGAGCACTAG",   # F8 (10 bp)
    "TGCCTTGATC",   # F9 (10 bp)
    "CTACTCAGTC",   # F10 (10 bp)
    "TCGTCTGACT",   # F11 (10 bp)
    "GAACATACGG",   # F12 (10 bp)
]

_R_BARCODES = [
    "CCCTATGACA",  # R1 (10 bp)
    "TAATGGCAAG",  # R2 (10 bp)
    "AACAAGGCGT",  # R3 (10 bp)
    "GTATGTAGAA",  # R4 (10 bp)
    "TTCTATGGGG",  # R5 (10 bp)
    "CCTCGCAACC",  # R6 (10 bp)
    "TGGATGCTTA",  # R7 (10 bp)
    "AGAGTGCGGC",  # R8 (10 bp)
]

_F_TAIL = "cacaggaggttaaacc"
_R_TAIL = "tgcgttgcgctctag"

# (name, prefix) tuples used by the anchored demux functions
_F_BC_TUPLES = [(f"isps_f_{i+1}", bc) for i, bc in enumerate(_F_BARCODES)]
_R_BC_TUPLES = [(f"isps_r_{i+1}", bc) for i, bc in enumerate(_R_BARCODES)]


# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------


@pytest.fixture()
def tmp_reference(tmp_path: Path) -> Path:
    ref_file = tmp_path / "reference.fasta"
    ref_file.write_text(f">sispS_test\n{_REF_SEQ}\n")
    return ref_file


@pytest.fixture()
def mock_barcodes_xlsx(tmp_path: Path) -> Path:
    """Write a minimal xlsx that load_barcode_prefixes / load_barcodes can read."""
    try:
        import openpyxl
    except ImportError:
        pytest.skip("openpyxl not available")

    wb = openpyxl.Workbook()
    ws = wb.active
    assert ws is not None, "Workbook has no active sheet"

    for i, bc in enumerate(_F_BARCODES, start=1):
        ws.append([f"isps_f_{i}", bc.lower() + _F_TAIL])
    for i, bc in enumerate(_R_BARCODES, start=1):
        ws.append([f"isps_r_{i}", bc.lower() + _R_TAIL])

    path = tmp_path / "barcodes.xlsx"
    wb.save(path)
    return path


def _make_fastq_gz(tmp_path: Path, reads: list[tuple[str, str]]) -> Path:
    """Write a gzipped FASTQ file and return its path."""
    fastq_path = tmp_path / "reads.fastq.gz"
    with gzip.open(fastq_path, "wt") as fh:
        for read_id, seq in reads:
            qual = "I" * len(seq)
            fh.write(f"@{read_id}\n{seq}\n+\n{qual}\n")
    return fastq_path


def _build_read(r_idx: int, f_idx: int, amplicon: str) -> str:
    """Build a synthetic read matching the real library layout (1-indexed).

    Real library structure (sense strand):
      5'-[F_barcode + F_anneal]-[insert]-[RC(R_anneal) + RC(R_barcode)]-3'

    Barcodes are stored in the xlsx on the construct sense strand.  The R barcode
    appears reverse-complemented at the 3-prime end of the sequenced read.
    """
    return (
        _F_BARCODES[f_idx - 1] + _F_TAIL
        + amplicon
        + _reverse_complement(_R_TAIL.upper()) + _reverse_complement(_R_BARCODES[r_idx - 1])
    )


# ---------------------------------------------------------------------------
# Unit tests: _extract_barcode_prefix
# ---------------------------------------------------------------------------


class TestExtractBarcodePrefix:
    def test_tail_present_returns_prefix(self) -> None:
        seq = "AATCCCACTACcacaggaggttaaacc"
        result = _extract_barcode_prefix(seq, "cacaggaggttaaacc")
        assert result == "AATCCCACTAC"

    def test_tail_absent_returns_first_11(self) -> None:
        seq = "AATCCCACTACXXXX"
        result = _extract_barcode_prefix(seq, "cacaggaggttaaacc")
        assert result == "AATCCCACTAC"

    def test_tail_case_insensitive(self) -> None:
        seq = "TTCTATGGGGtgcgttgcgctctag"
        result = _extract_barcode_prefix(seq, "tgcgttgcgctctag")
        assert result == "TTCTATGGGG"

    def test_short_seq_no_tail_returns_full(self) -> None:
        seq = "ABCDE"
        result = _extract_barcode_prefix(seq, "cacaggaggttaaacc")
        assert result == "ABCDE"


# ---------------------------------------------------------------------------
# Unit tests: load_barcode_prefixes
# ---------------------------------------------------------------------------


class TestLoadBarcodePrefixes:
    def test_returns_8_r_and_12_f(self, mock_barcodes_xlsx: Path) -> None:
        r_bc, f_bc = load_barcode_prefixes(mock_barcodes_xlsx)
        assert len(r_bc) == 8
        assert len(f_bc) == 12

    def test_r1_prefix_only(self, mock_barcodes_xlsx: Path) -> None:
        r_bc, _ = load_barcode_prefixes(mock_barcodes_xlsx)
        # R1 = "CCCTATGACA" prefix only (no tail)
        assert r_bc[0] == ("isps_r_1", "CCCTATGACA")

    def test_f1_prefix_only(self, mock_barcodes_xlsx: Path) -> None:
        _, f_bc = load_barcode_prefixes(mock_barcodes_xlsx)
        # F1 = "AATCCCACTAC" prefix only (11 bp)
        assert f_bc[0] == ("isps_f_1", "AATCCCACTAC")

    def test_sorted_by_index(self, mock_barcodes_xlsx: Path) -> None:
        r_bc, f_bc = load_barcode_prefixes(mock_barcodes_xlsx)
        assert f_bc[0] == ("isps_f_1", "AATCCCACTAC")   # F1
        assert f_bc[11] == ("isps_f_12", "GAACATACGG")  # F12
        assert r_bc[0] == ("isps_r_1", "CCCTATGACA")    # R1
        assert r_bc[7] == ("isps_r_8", "AGAGTGCGGC")    # R8

    def test_prefix_has_no_tail(self, mock_barcodes_xlsx: Path) -> None:
        r_bc, f_bc = load_barcode_prefixes(mock_barcodes_xlsx)
        for _, prefix in r_bc:
            assert _R_TAIL.upper() not in prefix
        for _, prefix in f_bc:
            assert _F_TAIL.upper() not in prefix


# ---------------------------------------------------------------------------
# Unit tests: load_barcodes (legacy full-sequence)
# ---------------------------------------------------------------------------


class TestLoadBarcodes:
    def test_returns_12_f_and_8_r(self, mock_barcodes_xlsx: Path) -> None:
        f_bc, r_bc = load_barcodes(mock_barcodes_xlsx)
        assert len(f_bc) == 12
        assert len(r_bc) == 8

    def test_f1_full_sequence(self, mock_barcodes_xlsx: Path) -> None:
        f_bc, _ = load_barcodes(mock_barcodes_xlsx)
        assert f_bc[0] == "AATCCCACTACCACAGGAGGTTAAACC"

    def test_r1_full_sequence(self, mock_barcodes_xlsx: Path) -> None:
        _, r_bc = load_barcodes(mock_barcodes_xlsx)
        assert r_bc[0] == "CCCTATGACATGCGTTGCGCTCTAG"


# ---------------------------------------------------------------------------
# Unit tests: _find_best_barcode
# ---------------------------------------------------------------------------


class TestFindBestBarcode:
    def test_exact_match_returns_correct_index(self) -> None:
        window = "XXXX" + _R_BARCODES[2] + "YYYY"  # R3 exact
        result = _find_best_barcode(_R_BC_TUPLES, window, edit_dist_ratio=0.15)
        assert result is not None
        assert result[0] == 3  # 1-based index for R3
        assert result[1] == 0  # edit distance 0

    def test_one_mismatch_accepted(self) -> None:
        # Introduce one mismatch in R1 prefix (10 bp, threshold = int(10*0.15) = 1)
        bc = _R_BARCODES[0]  # CCCTATGACA
        mutated = bc[:6] + "T" + bc[7:]  # 1 mismatch (G->T at pos 6: CCCTATTACA)
        window = "GGG" + mutated + "AAA"
        result = _find_best_barcode(_R_BC_TUPLES, window, edit_dist_ratio=0.15)
        assert result is not None
        assert result[0] == 1  # R1
        assert result[1] == 1  # edit distance 1

    def test_two_mismatches_rejected(self) -> None:
        # 2 mismatches on a 10 bp barcode: threshold = floor(10*0.15) = 1 -> rejected
        bc = _R_BARCODES[0]
        mutated = "A" + bc[1:6] + "T" + bc[7:]  # 2 mismatches (C->A pos0, G->T pos6: ACCTATTACA)
        window = "GGG" + mutated + "AAA"
        result = _find_best_barcode(_R_BC_TUPLES, window, edit_dist_ratio=0.15)
        assert result is None

    def test_no_barcode_in_window_returns_none(self) -> None:
        result = _find_best_barcode(_R_BC_TUPLES, "AAAAAAAAAAAAAAAA", edit_dist_ratio=0.15)
        assert result is None

    def test_ambiguous_equal_edit_distance_dropped(self) -> None:
        # Create a window that matches two barcodes with the same edit distance.
        # Use a sequence equidistant (1 edit) from both R1 and R2.
        # R1=CCCTATGACA, R2=TAATGGCAAG -- these differ substantially;
        # instead use two synthetic barcodes differing by 1 edit and check ambiguity.
        bc_a = "AAAAAAAAAA"
        bc_b = "AAAAAAAAAC"  # 1 edit from bc_a
        barcodes = [("bc_a", bc_a), ("bc_b", bc_b)]
        # Window contains bc_a exactly -> bc_a dist=0, bc_b dist=1 -> unambiguous
        result = _find_best_barcode(barcodes, "XXX" + bc_a + "YYY", edit_dist_ratio=0.15)
        assert result is not None
        assert result[0] == 1  # bc_a wins

    def test_ambiguous_tied_drops(self) -> None:
        # Both barcodes match with the same edit distance -> ambiguous -> drop
        bc_a = "AAAAAAAAAA"
        bc_b = "AAAAAAAAAT"  # 1 edit from bc_a
        barcodes = [("bc_a", bc_a), ("bc_b", bc_b)]
        # Window contains "AAAAAAAAAТ" which has dist=1 from both bc_a and bc_b
        # Actually need window that is 1 edit from both:
        # "AAAAAAAAAC" -> dist to bc_a=1, dist to bc_b=1 (tie)
        result = _find_best_barcode(barcodes, "XXX" + "AAAAAAAAAC" + "YYY", edit_dist_ratio=0.15)
        assert result is None


# ---------------------------------------------------------------------------
# Unit tests: _demux_read_anchored
# ---------------------------------------------------------------------------


class TestDemuxReadAnchored:
    def _make_aln_coords(self, read: str, amplicon: str) -> tuple[int, int]:
        """Return (q_st, q_en) for amplicon within read (exact substring)."""
        idx = read.find(amplicon)
        assert idx >= 0, "amplicon not found in read"
        return idx, idx + len(amplicon)

    def test_forward_strand_exact(self) -> None:
        read = _build_read(1, 1, _REF_SEQ)  # R1+Rtail+REF+F1+Ftail
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result == (1, 1)

    def test_forward_strand_r3_f5(self) -> None:
        read = _build_read(3, 5, _REF_SEQ)
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result == (3, 5)

    def test_minus_strand_rc_normalised(self) -> None:
        # Build +strand read, RC it, report strand=-1 and mappy-remapped coords
        fwd_read = _build_read(2, 4, _REF_SEQ)
        L = len(fwd_read)
        rc_read = _reverse_complement(fwd_read)
        # mappy q_st/q_en on rc_read: symmetric remap
        fwd_q_st, fwd_q_en = self._make_aln_coords(fwd_read, _REF_SEQ)
        # mappy on rc_read gives q_st = L - fwd_q_en, q_en = L - fwd_q_st
        rc_q_st = L - fwd_q_en
        rc_q_en = L - fwd_q_st
        result = _demux_read_anchored(
            read_seq=rc_read, q_st=rc_q_st, q_en=rc_q_en, strand=-1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result == (2, 4)

    def test_one_mismatch_in_r_barcode_still_matches(self) -> None:
        # Introduce 1 mismatch in R1 prefix (10 bp, threshold=1 edit)
        # R1=CCCTATGACA; change pos6 G->T: CCCTATTACA (1 real mismatch)
        r_prefix = _R_BARCODES[0]
        mutated_r = r_prefix[:6] + "T" + r_prefix[7:]  # 1 mismatch (G->T at pos6)
        # Real library: F+FTAIL + amplicon + RC(RTAIL) + RC(mutated_r)
        read = (
            _F_BARCODES[0] + _F_TAIL
            + _REF_SEQ
            + _reverse_complement(_R_TAIL.upper())
            + _reverse_complement(mutated_r)
        )
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result == (1, 1)

    def test_one_mismatch_in_f_barcode_still_matches(self) -> None:
        # F2=TGAACTGAGCG (11 bp, threshold=1); change pos5 T->A: TGAACAGAGCG
        f_prefix = _F_BARCODES[1]
        mutated_f = f_prefix[:5] + "A" + f_prefix[6:]
        # Real library: mutated_f + FTAIL + amplicon + RC(RTAIL) + RC(R1)
        read = (
            mutated_f + _F_TAIL
            + _REF_SEQ
            + _reverse_complement(_R_TAIL.upper())
            + _reverse_complement(_R_BARCODES[0])
        )
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result == (1, 2)

    def test_no_barcode_returns_none(self) -> None:
        # Read with only amplicon, no barcodes in windows
        read = "A" * 30 + _REF_SEQ + "A" * 30
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result is None

    def test_ambiguous_barcodes_dropped(self) -> None:
        # Two F barcodes 1 edit apart; place a sequence equidistant from both in the 5-prime window
        # bc_a="AAAAAAAAAA", bc_b="AAAAAAAAAT" (1 edit apart)
        # "AAAAAAAAAC" is 1 edit from both -> tied -> ambiguous -> drop
        bc_a = "AAAAAAAAAA"
        bc_b = "AAAAAAAAAT"  # 1 edit from bc_a
        ambiguous_f = [("a", bc_a), ("b", bc_b)]
        # Place "AAAAAAAAAC" (1 edit from both bc_a and bc_b) in the F-window (5-prime end)
        # Real layout: ambiguous_f_seq + REF + RC(RTAIL) + RC(R1)
        read = (
            "AAAAAAAAAC"
            + _REF_SEQ
            + _reverse_complement(_R_TAIL.upper())
            + _reverse_complement(_R_BARCODES[0])
        )
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=ambiguous_f,
        )
        assert result is None  # ambiguous F -> drop


# ---------------------------------------------------------------------------
# Unit tests: _demux_read (legacy exact-match)
# ---------------------------------------------------------------------------

# Full-sequence barcode lists as returned by load_barcodes (legacy).
_F_BARCODES_FULL = [bc + _F_TAIL.upper() for bc in _F_BARCODES]
_R_BARCODES_FULL = [bc + _R_TAIL.upper() for bc in _R_BARCODES]


class TestDemuxRead:
    def test_exact_fwd_match(self) -> None:
        seq = _R_BARCODES[0] + _R_TAIL + _REF_SEQ + _F_BARCODES[0] + _F_TAIL
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result == (1, 1)

    def test_rc_match(self) -> None:
        inner = _R_BARCODES[0] + _R_TAIL + _REF_SEQ + _F_BARCODES[1] + _F_TAIL
        seq = _reverse_complement(inner)
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result == (1, 2)

    def test_no_r_barcode_returns_none(self) -> None:
        seq = _REF_SEQ + _F_BARCODES[0] + _F_TAIL
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result is None

    def test_no_f_barcode_returns_none(self) -> None:
        seq = _R_BARCODES[0] + _R_TAIL + _REF_SEQ
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result is None

    def test_two_r_barcodes_returns_none(self) -> None:
        seq = (
            _R_BARCODES[0] + _R_TAIL
            + _R_BARCODES[1] + _R_TAIL
            + _REF_SEQ
            + _F_BARCODES[0] + _F_TAIL
        )
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result is None

    def test_correct_1based_index(self) -> None:
        seq = _R_BARCODES[2] + _R_TAIL + _REF_SEQ + _F_BARCODES[4] + _F_TAIL
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result == (3, 5)


# ---------------------------------------------------------------------------
# Integration tests: run_combinatorial_demux (synthetic end-to-end)
# ---------------------------------------------------------------------------


class TestRunCombinatorialDemux:
    def test_assigned_reads_and_wells(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads: list[tuple[str, str]] = []
        for i in range(5):
            reads.append((f"read_1_1_{i}", _build_read(1, 1, _REF_SEQ)))
        for i in range(3):
            reads.append((f"read_2_3_{i}", _build_read(2, 3, _REF_SEQ)))

        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        result = run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        assert result.stats.total_reads == 8
        assert result.stats.assigned_reads >= 1
        assert "1_1" in result.per_well_reads
        assert len(result.per_well_reads["1_1"]) >= 1

    def test_output_fasta_written(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads = [("r0", _build_read(1, 1, _REF_SEQ))]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        fasta_files = list(out_dir.glob("*.fasta"))
        assert len(fasta_files) >= 1

    def test_consensus_dir_created(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads = [("r0", _build_read(1, 1, _REF_SEQ))]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        assert (out_dir / "consensus").is_dir()

    def test_unassigned_reads_not_in_wells(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads = [("bare_read", _REF_SEQ)]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        result = run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        assert result.stats.assigned_reads == 0
        assert len(result.per_well_reads) == 0

    def test_ambiguous_drop_counted_in_stats(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        # Read with no barcode -> counted as ambiguous_dropped (no-match)
        reads = [("no_bc", _REF_SEQ)]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        result = run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            min_depth=1,
        )
        # All coverage-filtered reads that fail demux go to ambiguous_dropped
        assert result.stats.ambiguous_dropped >= 0  # counter exists
