# ruff: noqa: S101
"""Unit tests for kuma_core.mame.ingest.combinatorial_demux.

Coverage:
- load_barcode_prefixes: F/R prefix extraction from xlsx-like data
- load_barcodes: full-sequence loading (legacy backward compat)
- _find_best_barcode: exact match, 1-mismatch fuzzy, ambiguous drop
- _demux_read_anchored: anchor-based fuzzy demux, strand normalisation
- _demux_read: legacy exact-match (backward compat)
- run_combinatorial_demux: end-to-end with synthetic FASTQ + synthetic reference

Synthetic data strategy
-----------------------
Reference: 60 bp DNA (short enough to build synthetic reads quickly).
Reads: generated by embedding known F/R barcode prefixes around an amplicon
       that aligns to the reference at full span.
"""

from __future__ import annotations

import gzip
from pathlib import Path

import pytest

from kuma_core.mame.ingest.combinatorial_demux import (
    _demux_read,
    _demux_read_anchored,
    _find_best_barcode,
    _reverse_complement,
    load_barcode_prefixes,
    load_barcodes,
    run_combinatorial_demux,
)

# ---------------------------------------------------------------------------
# Synthetic constants
# ---------------------------------------------------------------------------

# Short synthetic reference (60 bp)
_REF_SEQ = "ATGGCTTGCTCTGTATCCACTGAGAACGTATCTTTCACTGAGACTGAAACTGAGACCCGT"

# Barcode prefix sequences (without annealing tails); matches xlsx structure.
_F_BARCODES = [
    "AATCCCACTAC",  # F1 (11 bp)
    "TGAACTGAGCG",  # F2 (11 bp)
    "TATCTGACCTT",  # F3 (11 bp)
    "ATATGAGACG",   # F4 (10 bp)
    "CGCTCATTAG",   # F5 (10 bp)
    "TAATCTCGTC",   # F6 (10 bp)
    "GCGCGATTTT",   # F7 (10 bp)
    "AGAGCACTAG",   # F8 (10 bp)
    "TGCCTTGATC",   # F9 (10 bp)
    "CTACTCAGTC",   # F10 (10 bp)
    "TCGTCTGACT",   # F11 (10 bp)
    "GAACATACGG",   # F12 (10 bp)
]

_R_BARCODES = [
    "CCCTATGACA",  # R1 (10 bp)
    "TAATGGCAAG",  # R2 (10 bp)
    "AACAAGGCGT",  # R3 (10 bp)
    "GTATGTAGAA",  # R4 (10 bp)
    "TTCTATGGGG",  # R5 (10 bp)
    "CCTCGCAACC",  # R6 (10 bp)
    "TGGATGCTTA",  # R7 (10 bp)
    "AGAGTGCGGC",  # R8 (10 bp)
]

_F_TAIL = "cacaggaggttaaacc"
_R_TAIL = "tgcgttgcgctctag"

# (name, prefix) tuples used by the anchored demux functions
_F_BC_TUPLES = [(f"isps_f_{i+1}", bc) for i, bc in enumerate(_F_BARCODES)]
_R_BC_TUPLES = [(f"isps_r_{i+1}", bc) for i, bc in enumerate(_R_BARCODES)]


# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------


@pytest.fixture()
def tmp_reference(tmp_path: Path) -> Path:
    ref_file = tmp_path / "reference.fasta"
    ref_file.write_text(f">sispS_test\n{_REF_SEQ}\n")
    return ref_file


@pytest.fixture()
def mock_barcodes_xlsx(tmp_path: Path) -> Path:
    """Write a minimal xlsx that load_barcode_prefixes / load_barcodes can read."""
    try:
        import openpyxl
    except ImportError:
        pytest.skip("openpyxl not available")

    wb = openpyxl.Workbook()
    ws = wb.active
    assert ws is not None, "Workbook has no active sheet"

    for i, bc in enumerate(_F_BARCODES, start=1):
        ws.append([f"isps_f_{i}", bc.lower() + _F_TAIL])
    for i, bc in enumerate(_R_BARCODES, start=1):
        ws.append([f"isps_r_{i}", bc.lower() + _R_TAIL])

    path = tmp_path / "barcodes.xlsx"
    wb.save(path)
    return path


def _make_fastq_gz(tmp_path: Path, reads: list[tuple[str, str]]) -> Path:
    """Write a gzipped FASTQ file and return its path."""
    fastq_path = tmp_path / "reads.fastq.gz"
    with gzip.open(fastq_path, "wt") as fh:
        for read_id, seq in reads:
            qual = "I" * len(seq)
            fh.write(f"@{read_id}\n{seq}\n+\n{qual}\n")
    return fastq_path


def _build_read(r_idx: int, f_idx: int, amplicon: str) -> str:
    """Build a synthetic read matching the real library layout (1-indexed).

    Real library structure (sense strand):
      5'-[F_barcode + F_anneal]-[insert]-[RC(R_anneal) + RC(R_barcode)]-3'

    Barcodes are stored in the xlsx on the construct sense strand.  The R barcode
    appears reverse-complemented at the 3-prime end of the sequenced read.
    """
    return (
        _F_BARCODES[f_idx - 1] + _F_TAIL
        + amplicon
        + _reverse_complement(_R_TAIL.upper()) + _reverse_complement(_R_BARCODES[r_idx - 1])
    )


# ---------------------------------------------------------------------------
# ``_extract_barcode_prefix`` used to be unit-tested here: "tail present returns
# the prefix", "tail absent returns the first 11 bp". The second case is exactly
# the fallback that was removed, and the function went with it. Deriving the
# tail from the axis is now the only rule, and it is tested against files rather
# than against a single sequence in
# ``tests/mame/test_barcode_prefix_derivation.py``, including the refusals that
# replaced those fallbacks.
#
# Unit tests: load_barcode_prefixes
# ---------------------------------------------------------------------------


class TestLoadBarcodePrefixes:
    def test_returns_8_r_and_12_f(self, mock_barcodes_xlsx: Path) -> None:
        r_bc, f_bc = load_barcode_prefixes(mock_barcodes_xlsx)
        assert len(r_bc) == 8
        assert len(f_bc) == 12

    def test_r1_prefix_only(self, mock_barcodes_xlsx: Path) -> None:
        r_bc, _ = load_barcode_prefixes(mock_barcodes_xlsx)
        # R1 = "CCCTATGACA" prefix only (no tail)
        assert r_bc[0] == ("isps_r_1", "CCCTATGACA")

    def test_f1_prefix_only(self, mock_barcodes_xlsx: Path) -> None:
        _, f_bc = load_barcode_prefixes(mock_barcodes_xlsx)
        # F1 = "AATCCCACTAC" prefix only (11 bp)
        assert f_bc[0] == ("isps_f_1", "AATCCCACTAC")

    def test_sorted_by_index(self, mock_barcodes_xlsx: Path) -> None:
        r_bc, f_bc = load_barcode_prefixes(mock_barcodes_xlsx)
        assert f_bc[0] == ("isps_f_1", "AATCCCACTAC")   # F1
        assert f_bc[11] == ("isps_f_12", "GAACATACGG")  # F12
        assert r_bc[0] == ("isps_r_1", "CCCTATGACA")    # R1
        assert r_bc[7] == ("isps_r_8", "AGAGTGCGGC")    # R8

    def test_prefix_has_no_tail(self, mock_barcodes_xlsx: Path) -> None:
        r_bc, f_bc = load_barcode_prefixes(mock_barcodes_xlsx)
        for _, prefix in r_bc:
            assert _R_TAIL.upper() not in prefix
        for _, prefix in f_bc:
            assert _F_TAIL.upper() not in prefix


# ---------------------------------------------------------------------------
# Unit tests: load_barcodes (legacy full-sequence)
# ---------------------------------------------------------------------------


class TestLoadBarcodes:
    def test_returns_12_f_and_8_r(self, mock_barcodes_xlsx: Path) -> None:
        f_bc, r_bc = load_barcodes(mock_barcodes_xlsx)
        assert len(f_bc) == 12
        assert len(r_bc) == 8

    def test_f1_full_sequence(self, mock_barcodes_xlsx: Path) -> None:
        f_bc, _ = load_barcodes(mock_barcodes_xlsx)
        assert f_bc[0] == "AATCCCACTACCACAGGAGGTTAAACC"

    def test_r1_full_sequence(self, mock_barcodes_xlsx: Path) -> None:
        _, r_bc = load_barcodes(mock_barcodes_xlsx)
        assert r_bc[0] == "CCCTATGACATGCGTTGCGCTCTAG"


# ---------------------------------------------------------------------------
# Unit tests: _find_best_barcode
# ---------------------------------------------------------------------------


class TestFindBestBarcode:
    def test_exact_match_returns_correct_index(self) -> None:
        window = "XXXX" + _R_BARCODES[2] + "YYYY"  # R3 exact
        result = _find_best_barcode(_R_BC_TUPLES, window, edit_dist_ratio=0.15)
        assert result is not None
        assert result[0] == 3  # 1-based index for R3
        assert result[1] == 0  # edit distance 0

    def test_one_mismatch_accepted(self) -> None:
        # Introduce one mismatch in R1 prefix (10 bp, threshold = int(10*0.15) = 1)
        bc = _R_BARCODES[0]  # CCCTATGACA
        mutated = bc[:6] + "T" + bc[7:]  # 1 mismatch (G->T at pos 6: CCCTATTACA)
        window = "GGG" + mutated + "AAA"
        result = _find_best_barcode(_R_BC_TUPLES, window, edit_dist_ratio=0.15)
        assert result is not None
        assert result[0] == 1  # R1
        assert result[1] == 1  # edit distance 1

    def test_two_mismatches_rejected(self) -> None:
        # 2 mismatches on a 10 bp barcode: threshold = floor(10*0.15) = 1 -> rejected
        bc = _R_BARCODES[0]
        mutated = "A" + bc[1:6] + "T" + bc[7:]  # 2 mismatches (C->A pos0, G->T pos6: ACCTATTACA)
        window = "GGG" + mutated + "AAA"
        result = _find_best_barcode(_R_BC_TUPLES, window, edit_dist_ratio=0.15)
        assert result is None

    def test_no_barcode_in_window_returns_none(self) -> None:
        result = _find_best_barcode(_R_BC_TUPLES, "AAAAAAAAAAAAAAAA", edit_dist_ratio=0.15)
        assert result is None

    def test_ambiguous_equal_edit_distance_dropped(self) -> None:
        # Create a window that matches two barcodes with the same edit distance.
        # Use a sequence equidistant (1 edit) from both R1 and R2.
        # R1=CCCTATGACA, R2=TAATGGCAAG -- these differ substantially;
        # instead use two synthetic barcodes differing by 1 edit and check ambiguity.
        bc_a = "AAAAAAAAAA"
        bc_b = "AAAAAAAAAC"  # 1 edit from bc_a
        barcodes = [("bc_a", bc_a), ("bc_b", bc_b)]
        # Window contains bc_a exactly -> bc_a dist=0, bc_b dist=1 -> unambiguous
        result = _find_best_barcode(barcodes, "XXX" + bc_a + "YYY", edit_dist_ratio=0.15)
        assert result is not None
        assert result[0] == 1  # bc_a wins

    def test_ambiguous_tied_drops(self) -> None:
        # Both barcodes match with the same edit distance -> ambiguous -> drop
        bc_a = "AAAAAAAAAA"
        bc_b = "AAAAAAAAAT"  # 1 edit from bc_a
        barcodes = [("bc_a", bc_a), ("bc_b", bc_b)]
        # Window contains "AAAAAAAAAТ" which has dist=1 from both bc_a and bc_b
        # Actually need window that is 1 edit from both:
        # "AAAAAAAAAC" -> dist to bc_a=1, dist to bc_b=1 (tie)
        result = _find_best_barcode(barcodes, "XXX" + "AAAAAAAAAC" + "YYY", edit_dist_ratio=0.15)
        assert result is None


# ---------------------------------------------------------------------------
# Unit tests: _demux_read_anchored
# ---------------------------------------------------------------------------


class TestDemuxReadAnchored:
    def _make_aln_coords(self, read: str, amplicon: str) -> tuple[int, int]:
        """Return (q_st, q_en) for amplicon within read (exact substring)."""
        idx = read.find(amplicon)
        assert idx >= 0, "amplicon not found in read"
        return idx, idx + len(amplicon)

    def test_forward_strand_exact(self) -> None:
        read = _build_read(1, 1, _REF_SEQ)  # R1+Rtail+REF+F1+Ftail
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result == (1, 1)

    def test_forward_strand_r3_f5(self) -> None:
        read = _build_read(3, 5, _REF_SEQ)
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result == (3, 5)

    def test_minus_strand_rc_normalised(self) -> None:
        # Build +strand read, RC it, report strand=-1 and mappy-remapped coords
        fwd_read = _build_read(2, 4, _REF_SEQ)
        L = len(fwd_read)
        rc_read = _reverse_complement(fwd_read)
        # mappy q_st/q_en on rc_read: symmetric remap
        fwd_q_st, fwd_q_en = self._make_aln_coords(fwd_read, _REF_SEQ)
        # mappy on rc_read gives q_st = L - fwd_q_en, q_en = L - fwd_q_st
        rc_q_st = L - fwd_q_en
        rc_q_en = L - fwd_q_st
        result = _demux_read_anchored(
            read_seq=rc_read, q_st=rc_q_st, q_en=rc_q_en, strand=-1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result == (2, 4)

    def test_one_mismatch_in_r_barcode_still_matches(self) -> None:
        # Introduce 1 mismatch in R1 prefix (10 bp, threshold=1 edit)
        # R1=CCCTATGACA; change pos6 G->T: CCCTATTACA (1 real mismatch)
        r_prefix = _R_BARCODES[0]
        mutated_r = r_prefix[:6] + "T" + r_prefix[7:]  # 1 mismatch (G->T at pos6)
        # Real library: F+FTAIL + amplicon + RC(RTAIL) + RC(mutated_r)
        read = (
            _F_BARCODES[0] + _F_TAIL
            + _REF_SEQ
            + _reverse_complement(_R_TAIL.upper())
            + _reverse_complement(mutated_r)
        )
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result == (1, 1)

    def test_one_mismatch_in_f_barcode_still_matches(self) -> None:
        # F2=TGAACTGAGCG (11 bp, threshold=1); change pos5 T->A: TGAACAGAGCG
        f_prefix = _F_BARCODES[1]
        mutated_f = f_prefix[:5] + "A" + f_prefix[6:]
        # Real library: mutated_f + FTAIL + amplicon + RC(RTAIL) + RC(R1)
        read = (
            mutated_f + _F_TAIL
            + _REF_SEQ
            + _reverse_complement(_R_TAIL.upper())
            + _reverse_complement(_R_BARCODES[0])
        )
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result == (1, 2)

    def test_no_barcode_returns_none(self) -> None:
        # Read with only amplicon, no barcodes in windows
        read = "A" * 30 + _REF_SEQ + "A" * 30
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result is None

    def test_ambiguous_barcodes_dropped(self) -> None:
        # Two F barcodes 1 edit apart; place a sequence equidistant from both in the 5-prime window
        # bc_a="AAAAAAAAAA", bc_b="AAAAAAAAAT" (1 edit apart)
        # "AAAAAAAAAC" is 1 edit from both -> tied -> ambiguous -> drop
        bc_a = "AAAAAAAAAA"
        bc_b = "AAAAAAAAAT"  # 1 edit from bc_a
        ambiguous_f = [("a", bc_a), ("b", bc_b)]
        # Place "AAAAAAAAAC" (1 edit from both bc_a and bc_b) in the F-window (5-prime end)
        # Real layout: ambiguous_f_seq + REF + RC(RTAIL) + RC(R1)
        read = (
            "AAAAAAAAAC"
            + _REF_SEQ
            + _reverse_complement(_R_TAIL.upper())
            + _reverse_complement(_R_BARCODES[0])
        )
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=ambiguous_f,
        )
        assert result is None  # ambiguous F -> drop

    def test_reference_start_does_not_leak_into_f_window(self) -> None:
        # Regression (F9 column contamination): the reference 5'-start
        # _REF_SEQ[1:11] == "TGGCTTGCTC" is edit distance 2 from the F9 prefix
        # "TGCCTTGATC" (_F_BARCODES[8]). A read whose forward barcode is
        # absent/degraded must NOT be assigned to F9 by matching the gene start.
        # The F search window must stop at the alignment anchor and exclude the
        # insert. R is a valid R1, so only the F side decides the result; before
        # the window fix this returned (1, 9) by matching the insert to F9.
        read = (
            "A" * 30                                  # 5' pad: no valid F barcode
            + _REF_SEQ                                # insert; starts ~ F9
            + _reverse_complement(_R_TAIL.upper())
            + _reverse_complement(_R_BARCODES[0])     # valid R1
        )
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result is None

    def test_real_f9_barcode_still_assigned(self) -> None:
        # Guard against over-correction: a genuine F9 barcode 5' of the anneal
        # tail must still be assigned to F9. The fix excludes the insert from the
        # window, not the barcode region, so real F9 reads are unaffected.
        read = (
            _F_BARCODES[8] + _F_TAIL                  # genuine F9 barcode
            + _REF_SEQ
            + _reverse_complement(_R_TAIL.upper())
            + _reverse_complement(_R_BARCODES[1])     # R2
        )
        q_st, q_en = self._make_aln_coords(read, _REF_SEQ)
        result = _demux_read_anchored(
            read_seq=read, q_st=q_st, q_en=q_en, strand=1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result == (2, 9)

    def test_reference_start_does_not_leak_into_f_window_minus_strand(self) -> None:
        # Same insert-collision guard on the reverse strand: build a +strand read
        # (no valid F barcode, valid R1), RC it, and report strand=-1 with the
        # mappy-remapped coords. Exercises the strand==-1 normalisation path so a
        # regression there cannot reopen the leak.
        fwd_read = (
            "A" * 30
            + _REF_SEQ
            + _reverse_complement(_R_TAIL.upper())
            + _reverse_complement(_R_BARCODES[0])     # valid R1
        )
        L = len(fwd_read)
        rc_read = _reverse_complement(fwd_read)
        fwd_q_st, fwd_q_en = self._make_aln_coords(fwd_read, _REF_SEQ)
        rc_q_st = L - fwd_q_en
        rc_q_en = L - fwd_q_st
        result = _demux_read_anchored(
            read_seq=rc_read, q_st=rc_q_st, q_en=rc_q_en, strand=-1,
            r_barcodes=_R_BC_TUPLES, f_barcodes=_F_BC_TUPLES,
        )
        assert result is None


# ---------------------------------------------------------------------------
# Unit tests: _demux_read (legacy exact-match)
# ---------------------------------------------------------------------------

# Full-sequence barcode lists as returned by load_barcodes (legacy).
_F_BARCODES_FULL = [bc + _F_TAIL.upper() for bc in _F_BARCODES]
_R_BARCODES_FULL = [bc + _R_TAIL.upper() for bc in _R_BARCODES]


class TestDemuxRead:
    def test_exact_fwd_match(self) -> None:
        seq = _R_BARCODES[0] + _R_TAIL + _REF_SEQ + _F_BARCODES[0] + _F_TAIL
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result == (1, 1)

    def test_rc_match(self) -> None:
        inner = _R_BARCODES[0] + _R_TAIL + _REF_SEQ + _F_BARCODES[1] + _F_TAIL
        seq = _reverse_complement(inner)
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result == (1, 2)

    def test_no_r_barcode_returns_none(self) -> None:
        seq = _REF_SEQ + _F_BARCODES[0] + _F_TAIL
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result is None

    def test_no_f_barcode_returns_none(self) -> None:
        seq = _R_BARCODES[0] + _R_TAIL + _REF_SEQ
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result is None

    def test_two_r_barcodes_returns_none(self) -> None:
        seq = (
            _R_BARCODES[0] + _R_TAIL
            + _R_BARCODES[1] + _R_TAIL
            + _REF_SEQ
            + _F_BARCODES[0] + _F_TAIL
        )
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result is None

    def test_correct_1based_index(self) -> None:
        seq = _R_BARCODES[2] + _R_TAIL + _REF_SEQ + _F_BARCODES[4] + _F_TAIL
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result == (3, 5)


# ---------------------------------------------------------------------------
# Integration tests: run_combinatorial_demux (synthetic end-to-end)
# ---------------------------------------------------------------------------


class TestRunCombinatorialDemux:
    def test_assigned_reads_and_wells(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads: list[tuple[str, str]] = []
        for i in range(5):
            reads.append((f"read_1_1_{i}", _build_read(1, 1, _REF_SEQ)))
        for i in range(3):
            reads.append((f"read_2_3_{i}", _build_read(2, 3, _REF_SEQ)))

        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        result = run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        assert result.stats.total_reads == 8
        assert result.stats.assigned_reads >= 1
        assert "1_1" in result.per_well_reads
        assert len(result.per_well_reads["1_1"]) >= 1

    def test_output_fasta_written(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads = [("r0", _build_read(1, 1, _REF_SEQ))]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        fasta_files = list(out_dir.glob("*.fasta"))
        assert len(fasta_files) >= 1

    def test_consensus_dir_created(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads = [("r0", _build_read(1, 1, _REF_SEQ))]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        assert (out_dir / "consensus").is_dir()

    def test_combined_consensus_fasta_written(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        from kuma_core.mame.ingest.combinatorial_demux import (
            _COMBINED_CONSENSUS_FILENAME,
        )

        reads = [
            ("r_2_3", _build_read(2, 3, _REF_SEQ)),
            ("r_1_1", _build_read(1, 1, _REF_SEQ)),
        ]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        result = run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        combined = out_dir / _COMBINED_CONSENSUS_FILENAME
        assert combined.is_file()

        # Parse the combined multi-record FASTA.
        headers: list[str] = []
        seqs: dict[str, str] = {}
        cur: str | None = None
        for line in combined.read_text().splitlines():
            if line.startswith(">"):
                cur = line[1:].strip()
                headers.append(cur)
                seqs[cur] = ""
            elif cur is not None:
                seqs[cur] += line.strip()

        # One record per well that produced a consensus; content matches.
        assert set(headers) == set(result.per_well_consensus)
        for wn, seq in result.per_well_consensus.items():
            assert seqs[wn] == seq
        # Records sorted by (R, F).
        assert headers == sorted(
            headers, key=lambda w: tuple(int(p) for p in w.split("_"))
        )

    def test_unassigned_reads_not_in_wells(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads = [("bare_read", _REF_SEQ)]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        result = run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        assert result.stats.assigned_reads == 0
        assert len(result.per_well_reads) == 0

    def test_ambiguous_drop_counted_in_stats(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        # Read with no barcode -> counted as ambiguous_dropped (no-match)
        reads = [("no_bc", _REF_SEQ)]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        result = run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            min_depth=1,
        )
        # All coverage-filtered reads that fail demux go to ambiguous_dropped
        assert result.stats.ambiguous_dropped >= 0  # counter exists


# ---------------------------------------------------------------------------
# New: progress_callback, MINIMAP2_THREADS constant, consensus equivalence
# ---------------------------------------------------------------------------


class TestProgressCallback:
    """Verify progress_callback is called during demux and consensus phases."""

    def test_demux_callback_invoked(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        """progress_callback receives at least one 'demux' call."""
        reads = [(_build_read(1, 1, _REF_SEQ),)] * 3  # type: ignore[list-item]
        actual_reads = [(f"r{i}", _build_read(1, 1, _REF_SEQ)) for i in range(3)]
        fastq = _make_fastq_gz(tmp_path, actual_reads)
        out_dir = tmp_path / "out"

        calls: list[tuple[int, int, str]] = []
        run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
            progress_callback=lambda cur, tot, stage: calls.append((cur, tot, stage)),
        )

        # At least one call per phase that has data
        assert any(s == "demux" for _, _, s in calls)
        # All calls must have non-negative current <= total
        for cur, tot, _ in calls:
            assert 0 <= cur <= tot

    def test_no_callback_ok(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        """progress_callback=None must not crash."""
        reads = [(f"r{i}", _build_read(1, 1, _REF_SEQ)) for i in range(2)]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"
        # Should complete without exception
        run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
            progress_callback=None,
        )


class TestConsensusParallelEquivalence:
    """Verify ThreadPool consensus produces the same result as serial computation.

    Mocks _compute_well_consensus and file I/O so minimap2 is not required.
    This test is NOT skipped when minimap2 is absent.
    """

    def test_parallel_matches_serial(self, tmp_path: Path) -> None:
        from unittest.mock import MagicMock, patch
        from pathlib import Path as _Path
        from kuma_core.mame.ingest.combinatorial_demux import (
            run_combinatorial_demux,
            _CONSENSUS_WORKERS,
        )

        ref_seq = _REF_SEQ
        ref_len = len(ref_seq)

        # Build per_well_reads-equivalent result without real alignment
        # by monkeypatching align_reads_multi and _compute_well_consensus
        reads_input = [(f"r{i}_{j}", _build_read(i + 1, j + 1, ref_seq))
                       for i in range(2) for j in range(2)]

        # Canonical serial consensus answers
        expected = {
            "1_1": ("AAACCC", 5, 0, 0.0, 0, 0.0, 0, 5, 5, 0, 0, 0, 0.0, 0, 0, 0),
            "1_2": ("TTTGGG", 3, 0, 0.0, 0, 0.0, 0, 3, 3, 0, 0, 0, 0.0, 0, 0, 0),
            "2_1": ("GGGAAA", 4, 0, 0.0, 0, 0.0, 0, 4, 4, 0, 0, 0, 0.0, 0, 0, 0),
            "2_2": ("CCCAAA", 2, 0, 0.0, 0, 0.0, 0, 2, 2, 0, 0, 0, 0.0, 0, 0, 0),
        }

        call_counts: dict[str, int] = {}

        def fake_consensus(well_name, reads, ref_fasta, ref_s, ref_l, min_d):
            call_counts[well_name] = call_counts.get(well_name, 0) + 1
            return expected[well_name]

        # Minimal DemuxStats / DemuxResult stubs via real run but patched internals
        from kuma_core.mame.ingest import combinatorial_demux as cd_mod

        def _consensus(*args: object) -> tuple:
            """Call through the module attribute so the patch below applies.

            The stub returns the 16 leading fields, not a full WellConsensus,
            and is handed a reference path where the real function takes
            alignments, so the call is deliberately untyped here.
            """
            return cd_mod._compute_well_consensus(*args)  # type: ignore[arg-type]

        # We patch at a higher level: provide fake per_well_reads by patching
        # the align functions to return empty (no reads pass) so per_well is
        # empty, which means consensus loop is skipped.
        # Instead, test the ThreadPool logic in isolation.

        # Build a per_well_reads dict with dummy entries for 4 wells
        import gzip, io
        from collections import defaultdict
        import concurrent.futures

        per_well_reads = {
            "1_1": [("r0", "A" * 10), ("r1", "A" * 10)],
            "1_2": [("r2", "T" * 10)],
            "2_1": [("r3", "G" * 10), ("r4", "G" * 10), ("r5", "G" * 10)],
            "2_2": [("r6", "C" * 10)],
        }

        # Fake reference fasta
        ref_fasta = tmp_path / "ref.fasta"
        ref_fasta.write_text(f">ref\n{_REF_SEQ}\n")
        (tmp_path / "consensus").mkdir()

        # Run parallel version directly
        result_parallel: dict[str, str] = {}
        result_serial: dict[str, str] = {}

        with patch.object(cd_mod, "_compute_well_consensus", side_effect=fake_consensus):
            # Serial reference
            for wn, rds in per_well_reads.items():
                (
                    seq,
                    depth,
                    mixed_positions,
                    max_minor_fraction,
                    low_depth_positions,
                    n_fraction,
                    low_quality_bases,
                    input_reads,
                    aligned_reads,
                    mapq_failed,
                    span_failed,
                    n_indel_event_positions,
                    max_indel_event_fraction,
                    max_del_run_length,
                    consensus_net_indel,
                    read_net_indel,
                ) = _consensus(
                    wn, rds, ref_fasta, ref_seq, ref_len, 1
                )
                result_serial[wn] = seq
                (tmp_path / "consensus" / f"{wn}.fasta").write_text(
                    f">{wn} depth={depth} input_reads={input_reads} "
                    f"aligned_reads={aligned_reads} mapq_failed={mapq_failed} "
                    f"span_failed={span_failed} mixed_positions={mixed_positions} "
                    f"max_minor_allele_fraction={max_minor_fraction:.3f} "
                    f"low_depth_positions={low_depth_positions} "
                    f"consensus_n_fraction={n_fraction:.3f} "
                    f"low_quality_bases={low_quality_bases} "
                    f"consensus_net_indel={consensus_net_indel} "
                    f"read_net_indel={read_net_indel}\n{seq}\n"
                )

        call_counts.clear()

        with patch.object(cd_mod, "_compute_well_consensus", side_effect=fake_consensus):
            # Parallel version
            done = 0
            with concurrent.futures.ThreadPoolExecutor(max_workers=_CONSENSUS_WORKERS) as pool:
                futures = {
                    pool.submit(_consensus, wn, rds,
                                ref_fasta, ref_seq, ref_len, 1): wn
                    for wn, rds in per_well_reads.items()
                }
                for fut in concurrent.futures.as_completed(futures):
                    seq = fut.result()[0]
                    result_parallel[futures[fut]] = seq
                    done += 1

        # Both produce identical per-well sequences
        assert result_parallel == result_serial, (
            f"Parallel != serial: {result_parallel!r} vs {result_serial!r}"
        )
        # Each well called exactly once in each path
        assert set(call_counts.keys()) == set(per_well_reads.keys())


class TestMinimap2ThreadsConstant:
    """Verify _MINIMAP2_THREADS reads from env var or falls back to cpu-based default."""

    def test_env_var_takes_priority(self, monkeypatch: pytest.MonkeyPatch) -> None:
        import importlib
        import kuma_core.mame.ingest.align as align_mod

        monkeypatch.setenv("KUMA_MINIMAP2_THREADS", "3")
        # Reload to pick up env change (module-level constant)
        importlib.reload(align_mod)
        assert align_mod._MINIMAP2_THREADS == 3
        # Restore default
        monkeypatch.delenv("KUMA_MINIMAP2_THREADS", raising=False)
        importlib.reload(align_mod)

    def test_default_within_bounds(self) -> None:
        import os

        from kuma_core.mame.ingest.align import _MINIMAP2_THREADS

        # Auto-detected default: all host cores minus one reserved for the UI.
        assert _MINIMAP2_THREADS == max(1, (os.cpu_count() or 4) - 1)


# ---------------------------------------------------------------------------
# Barcode-window extraction equivalence (perf refactor regression guard)
# ---------------------------------------------------------------------------

import random  # noqa: E402

from kuma_core.mame.ingest.combinatorial_demux import (  # noqa: E402
    _extract_barcode_windows,
)

# Independent reverse-complement for the reference implementation, so the
# reference does not inherit a bug from the production helper it guards.
_REF_COMP = str.maketrans("ACGTacgtNn", "TGCAtgcaNn")


def _ref_rc(seq: str) -> str:
    return seq.translate(_REF_COMP)[::-1]


def _reference_windows_pre_refactor(
    read_seq: str,
    q_st: int,
    q_en: int,
    strand: int,
    window_bp: int,
    max_f_len: int,
    max_r_len: int,
) -> tuple[str, str]:
    """Pre-refactor window formula, transcribed verbatim as a test oracle.

    The original code upper()'d (and, on strand -1, reverse-complemented) the
    *whole* read, normalised the anchor coordinates, then sliced.  The shipped
    helper slices first and normalises only the two short slices.  This oracle
    is written out by hand on purpose: the original implementation no longer
    exists in the tree, so it cannot be imported.
    """
    seq = read_seq.upper()
    L = len(seq)
    if strand == -1:
        seq = _ref_rc(seq)
        norm_q_st = L - q_en
        norm_q_en = L - q_st
    else:
        norm_q_st = q_st
        norm_q_en = q_en
    f_window = seq[max(0, norm_q_st - window_bp - max_f_len):min(L, norm_q_st)]
    r_window = seq[max(0, norm_q_en):min(L, norm_q_en + window_bp + max_r_len)]
    return f_window, r_window


_WINDOW_ALPHABET = "ACGTacgtNn"
_WINDOW_LENGTHS = (0, 1, 2, 5, 20, 45, 46, 47, 60, 150)
_WINDOW_BPS = (0, 1, 30)
_WINDOW_MAX_LENS = ((11, 10), (0, 0), (16, 15))
_WINDOW_STRANDS = (1, -1)
# Enumerate every (q_st, q_en) pair up to this read length; sample above it.
_WINDOW_FULL_ENUM_MAX_L = 20
_WINDOW_SAMPLED_PAIRS = 200
_WINDOW_SEQS_PER_LENGTH = 2
_WINDOW_SEED = 20260731


def _anchor_pairs(rng: random.Random, L: int) -> list[tuple[int, int]]:
    """Anchor (q_st, q_en) pairs for read length *L*: boundaries + sampling."""
    # Boundary cases are included unconditionally, never left to sampling.
    pairs: set[tuple[int, int]] = {
        (0, 0),          # empty alignment at the 5' end
        (0, L),          # alignment spans the whole read
        (L, L),          # empty alignment at the 3' end
    }
    for x in (0, 1, L // 2, L - 1, L):
        if 0 <= x <= L:
            pairs.add((x, x))            # q_st == q_en
            pairs.add((x, L))            # q_en == L
            pairs.add((0, x))            # q_st == 0
    if L <= _WINDOW_FULL_ENUM_MAX_L:
        for q_st in range(L + 1):
            for q_en in range(q_st, L + 1):
                pairs.add((q_st, q_en))
    else:
        for _ in range(_WINDOW_SAMPLED_PAIRS):
            a = rng.randint(0, L)
            b = rng.randint(0, L)
            pairs.add((min(a, b), max(a, b)))
    return sorted(pairs)


def test_extract_barcode_windows_matches_pre_refactor_formula() -> None:
    """Regression guard: the slice-then-normalise window extraction in
    ``_extract_barcode_windows`` must return byte-identical f/r windows to the
    original upper()/RC()-the-whole-read formula, so the hot-loop perf refactor
    cannot silently shift barcode search windows and mis-assign wells.
    """
    rng = random.Random(_WINDOW_SEED)
    checked = 0
    for L in _WINDOW_LENGTHS:
        seqs = [
            "".join(rng.choice(_WINDOW_ALPHABET) for _ in range(L))
            for _ in range(_WINDOW_SEQS_PER_LENGTH)
        ]
        for q_st, q_en in _anchor_pairs(rng, L):
            assert 0 <= q_st <= q_en <= L
            for strand in _WINDOW_STRANDS:
                for window_bp in _WINDOW_BPS:
                    for max_f_len, max_r_len in _WINDOW_MAX_LENS:
                        for read_seq in seqs:
                            expected = _reference_windows_pre_refactor(
                                read_seq, q_st, q_en, strand,
                                window_bp, max_f_len, max_r_len,
                            )
                            actual = _extract_barcode_windows(
                                read_seq, q_st, q_en, strand,
                                window_bp, max_f_len, max_r_len,
                            )
                            assert actual == expected, (
                                f"L={L} q_st={q_st} q_en={q_en} "
                                f"strand={strand} window_bp={window_bp} "
                                f"max_f_len={max_f_len} max_r_len={max_r_len} "
                                f"read={read_seq!r}"
                            )
                            checked += 1
    # Guard against the sampling silently collapsing to a trivial case count.
    assert checked > 20000, checked


def test_extract_barcode_windows_is_used_by_demux_read_anchored() -> None:
    """Regression guard: _demux_read_anchored must route through the shared
    window helper, so the equivalence test above actually covers production.
    """
    calls: list[tuple[object, ...]] = []
    import kuma_core.mame.ingest.combinatorial_demux as mod

    original = mod._extract_barcode_windows

    def _spy(*args: object) -> tuple[str, str]:
        calls.append(args)
        return original(*args)  # type: ignore[arg-type]

    mod._extract_barcode_windows = _spy  # type: ignore[assignment]
    try:
        _demux_read_anchored(
            "ACGT" * 40,
            q_st=20,
            q_en=100,
            strand=1,
            r_barcodes=[("R1", _R_BARCODES[0])],
            f_barcodes=[("F1", _F_BARCODES[0])],
        )
    finally:
        mod._extract_barcode_windows = original  # type: ignore[assignment]

    assert len(calls) == 1


@pytest.mark.parametrize("chimera_split", [True, False])
def test_coverage_wipeout_is_not_reported_as_a_mapq_wipeout(
    tmp_path: Path, mock_barcodes_xlsx: Path, chimera_split: bool
) -> None:
    """passed_mapq and passed_coverage must count DIFFERENT gates.

    Reads carrying only the first 60 bp of a 660 bp reference align uniquely
    (so they clear MAPQ) but cover 9% of the reference (so they all die at the
    0.98 coverage gate).  Both counters used to be set to the post-filter count,
    which made this look like a MAPQ wipeout in the marker stats.
    """
    import random

    rng = random.Random(20260804)
    filler = "".join(rng.choice("ACGT") for _ in range(600))
    reference = tmp_path / "long_reference.fasta"
    reference.write_text(f">long_ref\n{_REF_SEQ}{filler}\n")

    reads = [(f"r{i}", _build_read(1, 1, _REF_SEQ)) for i in range(8)]
    fastq = _make_fastq_gz(tmp_path, reads)

    result = run_combinatorial_demux(
        raw_fastq_paths=[fastq],
        reference_fasta=reference,
        barcodes_xlsx=mock_barcodes_xlsx,
        output_dir=tmp_path / "out",
        mapq_threshold=0,
        coverage_fraction=0.98,
        trim_flank_bp=30,
        min_depth=1,
        chimera_split=chimera_split,
    )

    assert result.stats.total_reads == 8
    assert result.stats.passed_mapq > 0
    assert result.stats.passed_coverage == 0
    assert result.stats.assigned_reads == 0


def test_marker_resume_uses_the_coverage_gate_not_the_mapq_gate() -> None:
    """A completed unit whose reads all died at the coverage gate is re-run.

    Markers written before the two gates were counted separately carry equal
    values in both counters, so their verdict is unchanged.
    """
    from kuma_core.mame.ingest.combinatorial_demux import _marker_has_usable_alignment

    # New-format marker: cleared MAPQ, wiped out at the coverage gate.
    assert not _marker_has_usable_alignment(
        {"stats": {"total_reads": 100, "passed_mapq": 100, "passed_coverage": 0}}
    )
    assert _marker_has_usable_alignment(
        {"stats": {"total_reads": 100, "passed_mapq": 100, "passed_coverage": 40}}
    )
    # Legacy marker shape (both counters equal) and the empty-unit case.
    assert not _marker_has_usable_alignment(
        {"stats": {"total_reads": 100, "passed_mapq": 0, "passed_coverage": 0}}
    )
    assert _marker_has_usable_alignment(
        {"stats": {"total_reads": 0, "passed_mapq": 0, "passed_coverage": 0}}
    )
    assert _marker_has_usable_alignment({})
