# ruff: noqa: S101
"""Unit tests for kuma_core.mame.ingest.combinatorial_demux.

Coverage:
- _extract_barcode_prefix: tail present / tail absent fallback
- load_barcodes: F/R prefix extraction from xlsx-like data
- _demux_read: exact-match fwd, exact-match RC, ambiguous drop, no-match drop
- run_combinatorial_demux: end-to-end with synthetic FASTQ + synthetic reference

Synthetic data strategy
-----------------------
Reference: 60 bp DNA (short enough to build synthetic reads quickly).
Reads: generated by embedding known F/R barcode prefixes around an amplicon
       that aligns to the reference at full span.
"""

from __future__ import annotations

import gzip
from pathlib import Path

import pytest

from kuma_core.mame.ingest.combinatorial_demux import (
    _demux_read,
    _extract_barcode_prefix,
    _reverse_complement,
    load_barcodes,
    run_combinatorial_demux,
)

# ---------------------------------------------------------------------------
# Synthetic constants
# ---------------------------------------------------------------------------

# Short synthetic reference (60 bp)
_REF_SEQ = "ATGGCTTGCTCTGTATCCACTGAGAACGTATCTTTCACTGAGACTGAAACTGAGACCCGT"
# Barcode prefixes matching the xlsx structure (without annealing tails)
_F_BARCODES = [
    "AATCCCACTAC",  # F1
    "TGAACTGAGCG",  # F2
    "TATCTGACCTT",  # F3
    "ATATGAGACG",   # F4
    "CGCTCATTAG",   # F5
    "TAATCTCGTC",   # F6
    "GCGCGATTTT",   # F7
    "AGAGCACTAG",   # F8
    "TGCCTTGATC",   # F9
    "CTACTCAGTC",   # F10
    "TCGTCTGACT",   # F11
    "GAACATACGG",   # F12
]

_R_BARCODES = [
    "CCCTATGACA",  # R1
    "TAATGGCAAG",  # R2
    "AACAAGGCGT",  # R3
    "GTATGTAGAA",  # R4
    "TTCTATGGGG",  # R5
    "CCTCGCAACC",  # R6
    "TGGATGCTTA",  # R7
    "AGAGTGCGGC",  # R8
]


# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------


@pytest.fixture()
def tmp_reference(tmp_path: Path) -> Path:
    ref_file = tmp_path / "reference.fasta"
    ref_file.write_text(f">sispS_test\n{_REF_SEQ}\n")
    return ref_file


@pytest.fixture()
def mock_barcodes_xlsx(tmp_path: Path) -> Path:
    """Write a minimal xlsx that load_barcodes can read."""
    try:
        import openpyxl
    except ImportError:
        pytest.skip("openpyxl not available")

    wb = openpyxl.Workbook()
    ws = wb.active
    assert ws is not None, "Workbook has no active sheet"
    f_tail = "cacaggaggttaaacc"
    r_tail = "tgcgttgcgctctag"

    for i, bc in enumerate(_F_BARCODES, start=1):
        ws.append([f"isps_f_{i}", bc.lower() + f_tail])
    for i, bc in enumerate(_R_BARCODES, start=1):
        ws.append([f"isps_r_{i}", bc.lower() + r_tail])

    path = tmp_path / "barcodes.xlsx"
    wb.save(path)
    return path


def _make_fastq_gz(tmp_path: Path, reads: list[tuple[str, str]]) -> Path:
    """Write a gzipped FASTQ file and return its path."""
    fastq_path = tmp_path / "reads.fastq.gz"
    with gzip.open(fastq_path, "wt") as fh:
        for read_id, seq in reads:
            qual = "I" * len(seq)
            fh.write(f"@{read_id}\n{seq}\n+\n{qual}\n")
    return fastq_path


_F_TAIL = "cacaggaggttaaacc"
_R_TAIL = "tgcgttgcgctctag"


def _build_read(r_idx: int, f_idx: int, amplicon: str) -> str:
    """Build a synthetic read: R_barcode+tail + amplicon + F_barcode+tail (1-indexed).

    Tails are included so that load_barcodes (now returning full sequences)
    can find them as substrings.
    """
    return _R_BARCODES[r_idx - 1] + _R_TAIL + amplicon + _F_BARCODES[f_idx - 1] + _F_TAIL


# ---------------------------------------------------------------------------
# Unit tests: _extract_barcode_prefix
# ---------------------------------------------------------------------------


class TestExtractBarcodePrefix:
    def test_tail_present_returns_prefix(self) -> None:
        seq = "AATCCCACTACcacaggaggttaaacc"
        result = _extract_barcode_prefix(seq, "cacaggaggttaaacc")
        assert result == "AATCCCACTAC"

    def test_tail_absent_returns_first_11(self) -> None:
        seq = "AATCCCACTACXXXX"
        result = _extract_barcode_prefix(seq, "cacaggaggttaaacc")
        assert result == "AATCCCACTAC"

    def test_tail_case_insensitive(self) -> None:
        seq = "TTCTATGGGGtgcgttgcgctctag"
        result = _extract_barcode_prefix(seq, "tgcgttgcgctctag")
        assert result == "TTCTATGGGG"

    def test_short_seq_no_tail_returns_full(self) -> None:
        seq = "ABCDE"
        result = _extract_barcode_prefix(seq, "cacaggaggttaaacc")
        assert result == "ABCDE"


# ---------------------------------------------------------------------------
# Unit tests: load_barcodes
# ---------------------------------------------------------------------------


class TestLoadBarcodes:
    def test_returns_12_f_and_8_r(self, mock_barcodes_xlsx: Path) -> None:
        f_bc, r_bc = load_barcodes(mock_barcodes_xlsx)
        assert len(f_bc) == 12
        assert len(r_bc) == 8

    def test_f1_prefix_correct(self, mock_barcodes_xlsx: Path) -> None:
        f_bc, _ = load_barcodes(mock_barcodes_xlsx)
        assert f_bc[0] == "AATCCCACTACCACAGGAGGTTAAACC"

    def test_r1_prefix_correct(self, mock_barcodes_xlsx: Path) -> None:
        _, r_bc = load_barcodes(mock_barcodes_xlsx)
        assert r_bc[0] == "CCCTATGACATGCGTTGCGCTCTAG"

    def test_sorted_by_index(self, mock_barcodes_xlsx: Path) -> None:
        f_bc, r_bc = load_barcodes(mock_barcodes_xlsx)
        assert f_bc[0] == "AATCCCACTACCACAGGAGGTTAAACC"   # F1
        assert f_bc[11] == "GAACATACGGCACAGGAGGTTAAACC"   # F12
        assert r_bc[0] == "CCCTATGACATGCGTTGCGCTCTAG"    # R1
        assert r_bc[7] == "AGAGTGCGGCTGCGTTGCGCTCTAG"    # R8


# ---------------------------------------------------------------------------
# Unit tests: _demux_read
# ---------------------------------------------------------------------------


# Full-sequence barcode lists as returned by load_barcodes after this change.
# Each entry = barcode prefix + annealing tail (uppercase).
_F_BARCODES_FULL = [bc + _F_TAIL.upper() for bc in _F_BARCODES]
_R_BARCODES_FULL = [bc + _R_TAIL.upper() for bc in _R_BARCODES]


class TestDemuxRead:
    def test_exact_fwd_match(self) -> None:
        # Read contains full F/R sequences (prefix + tail)
        seq = _R_BARCODES[0] + _R_TAIL + _REF_SEQ + _F_BARCODES[0] + _F_TAIL
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result == (1, 1)

    def test_rc_match(self) -> None:
        # Build a read where R1 + REF + F2 appear; take RC and confirm demux
        inner = _R_BARCODES[0] + _R_TAIL + _REF_SEQ + _F_BARCODES[1] + _F_TAIL
        seq = _reverse_complement(inner)
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        # Searching RC(seq) == inner finds R1 and F2
        assert result == (1, 2)

    def test_no_r_barcode_returns_none(self) -> None:
        seq = _REF_SEQ + _F_BARCODES[0] + _F_TAIL
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result is None

    def test_no_f_barcode_returns_none(self) -> None:
        seq = _R_BARCODES[0] + _R_TAIL + _REF_SEQ
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result is None

    def test_two_r_barcodes_returns_none(self) -> None:
        seq = _R_BARCODES[0] + _R_TAIL + _R_BARCODES[1] + _R_TAIL + _REF_SEQ + _F_BARCODES[0] + _F_TAIL
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result is None

    def test_correct_1based_index(self) -> None:
        seq = _R_BARCODES[2] + _R_TAIL + _REF_SEQ + _F_BARCODES[4] + _F_TAIL
        result = _demux_read(seq, _F_BARCODES_FULL, _R_BARCODES_FULL)
        assert result == (3, 5)


# ---------------------------------------------------------------------------
# Integration tests: run_combinatorial_demux (synthetic end-to-end)
# ---------------------------------------------------------------------------


class TestRunCombinatorialDemux:
    def test_assigned_reads_and_wells(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads: list[tuple[str, str]] = []
        for i in range(5):
            reads.append((f"read_1_1_{i}", _build_read(1, 1, _REF_SEQ)))
        for i in range(3):
            reads.append((f"read_2_3_{i}", _build_read(2, 3, _REF_SEQ)))

        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        result = run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        assert result.stats.total_reads == 8
        assert result.stats.assigned_reads >= 1
        assert "1_1" in result.per_well_reads
        assert len(result.per_well_reads["1_1"]) >= 1

    def test_output_fasta_written(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads = [("r0", _build_read(1, 1, _REF_SEQ))]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        fasta_files = list(out_dir.glob("*.fasta"))
        assert len(fasta_files) >= 1

    def test_consensus_dir_created(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads = [("r0", _build_read(1, 1, _REF_SEQ))]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        assert (out_dir / "consensus").is_dir()

    def test_unassigned_reads_not_in_wells(
        self, tmp_path: Path, tmp_reference: Path, mock_barcodes_xlsx: Path
    ) -> None:
        reads = [("bare_read", _REF_SEQ)]
        fastq = _make_fastq_gz(tmp_path, reads)
        out_dir = tmp_path / "out"

        result = run_combinatorial_demux(
            raw_fastq_paths=[fastq],
            reference_fasta=tmp_reference,
            barcodes_xlsx=mock_barcodes_xlsx,
            output_dir=out_dir,
            mapq_threshold=0,
            coverage_fraction=0.5,
            trim_flank_bp=30,
            min_depth=1,
        )

        assert result.stats.assigned_reads == 0
        assert len(result.per_well_reads) == 0
